using System.Collections.Generic;

namespace TikMan.App.Localization;

/// <summary>Translation tables. Both dictionaries must have the same keys.
/// Placeholders {0}, {1} … are filled via LocalizationManager.T(key, args).</summary>
internal static class Strings
{
    public static readonly Dictionary<string, string> German = new()
    {
        // Toolbar
        ["Tb_Scan"] = "🔍 Scannen…",
        ["Tb_Add"] = "➕ Hinzufügen",
        ["Tb_Edit"] = "✏️ Bearbeiten",
        ["Tb_Remove"] = "🗑️ Entfernen",
        ["Tb_RefreshAll"] = "🔄 Alle abfragen",
        ["Tb_BackupAll"] = "💾 Backups sichern…",
        ["Tb_CheckUpdates"] = "📦 Updates prüfen",
        ["Tb_InstallUpdates"] = "⬆️ Updates installieren…",
        ["Tb_Settings"] = "⚙️ Einstellungen…",
        ["Tb_AutoRefresh"] = "Auto-Abfrage alle",

        // Device table
        ["Col_Name"] = "Name",
        ["Col_Address"] = "Adresse",
        ["Col_Board"] = "Board",
        ["Col_Version"] = "Version",
        ["Col_Latest"] = "Neuste",
        ["Col_Cpu"] = "CPU",
        ["Col_Ram"] = "RAM",
        ["Col_Uptime"] = "Uptime",
        ["Col_LastError"] = "Letzter Fehler",

        // Tabs
        ["Tab_Logs"] = "Logs",
        ["Tab_Monitoring"] = "CPU / RAM-Auslastung",
        ["Tab_Update"] = "Update",
        ["Tab_Details"] = "Details",

        // Logs
        ["Logs_Load"] = "🔄 Logs aktualisieren",
        ["Logs_Count"] = "Anzahl:",
        ["Logs_All"] = "alle",
        ["Logs_Filter"] = "Filter:",
        ["Col_Time"] = "Zeit",
        ["Col_Topics"] = "Topics",
        ["Col_Message"] = "Meldung",

        // Monitoring
        ["Chart_NoData"] = "Noch keine Messwerte – Gerät wird beim nächsten Abfragen erfasst.",
        ["Col_Protocol"] = "Protokoll",
        ["Sc_Clear"] = "🗑️ Leeren",
        ["Sc_CredsHint"] = "Neue Geräte verwenden die Standard-Zugangsdaten aus den Einstellungen.",
        ["Set_DefaultPwHint"] = "Leer lassen = aktuelles Passwort behalten.",

        // Gerätestatus / kurze Update-Status
        ["St_Online"] = "Online",
        ["St_Offline"] = "Offline",
        ["St_Busy"] = "Beschäftigt…",
        ["St_Unknown"] = "Unbekannt",
        ["Upd_CheckFailedStatus"] = "Prüfung fehlgeschlagen",
        ["Upd_ChannelFailedStatus"] = "Kanalwechsel fehlgeschlagen",

        // Update tab
        ["Upd_Installed"] = "Installierte Version:",
        ["Upd_Latest"] = "Neuste Version:",
        ["Upd_Channel"] = "Kanal:",
        ["Upd_Status"] = "Status:",
        ["Upd_ChannelLabel"] = "Update-Kanal:",
        ["Upd_ChannelHint"] = "Auswahl wird sofort gesetzt und geprüft.",
        ["Upd_Check"] = "Update prüfen",
        ["Upd_Install"] = "Update installieren (rebootet!)",
        ["Upd_Note"] = "Hinweis: Ein RouterOS-Update lädt die Pakete herunter und startet das Gerät neu. Für mehrere Geräte den Assistenten «Updates installieren…» in der Werkzeugleiste verwenden – dort wird sequenziell installiert und gewartet, bis jedes Gerät wieder online ist.",
        ["Upd_RightsBox"] = "Benötigte Rechte des API-Benutzers:\n• Nur Überwachen/Logs/Update prüfen: read, rest-api\n• Kanal wechseln & Update installieren: zusätzlich write, reboot, test\n• Config-Backup (.rsc): über HTTPS mit write (temporäre Exportdatei) – kein FTP nötig\n• Voll-Backup (.backup) via SSH: zusätzlich ssh, ftp (SSH-Dienst aktiv)",

        // Details tab
        ["Det_Connection"] = "Verbindung:",
        ["Det_User"] = "Benutzer:",
        ["Det_Mac"] = "MAC:",
        ["Det_Notes"] = "Notizen:",
        ["Det_Edit"] = "✏️ Gerät bearbeiten…",
        ["Det_BackupRsc"] = "💾 Config-Backup (.rsc)…",
        ["Det_BackupFull"] = "🗄️ Voll-Backup (.backup)…",
        ["Det_BackupDesc"] = "Config-Backup (.rsc): vollständige, lesbare Konfiguration über HTTPS – ohne Passwörter/Keys, ideal zum Versionieren, mit /import wiederherstellbar. Voll-Backup (.backup): exakte Binärkopie inkl. Passwörtern; Download je nach Einstellung über Web/WebFig oder SSH (nicht über die REST-API möglich).",

        // Status bar / messages (MainWindow)
        ["Status_Ready"] = "Bereit",
        ["Msg_NoDevices"] = "Keine Geräte konfiguriert – mit «Scannen…» das Netzwerk durchsuchen oder «Hinzufügen» klicken.",
        ["Msg_SelectDeviceFirst"] = "Zuerst ein Gerät auswählen.",
        ["Msg_Querying"] = "Frage {0} Gerät(e) ab…",
        ["Msg_OnlineSummary"] = "{0} – {1}/{2} Geräte online",
        ["Msg_UpdatesAvailableSuffix"] = ", {0} Update(s) verfügbar",
        ["Msg_DevicesAdded"] = "{0} Gerät(e) hinzugefügt.",
        ["Msg_RemoveConfirm"] = "«{0}» ({1}) wirklich aus der Überwachung entfernen?\nAm Gerät selbst wird nichts geändert.",
        ["Msg_RemoveTitle"] = "Gerät entfernen",
        ["Msg_LoadingLogs"] = "Lade Logs von {0}…",
        ["Msg_LogsLoaded"] = "{0} Logeinträge von {1} geladen.",
        ["Msg_LogsFailed"] = "Logs von {0} konnten nicht geladen werden: {1}",
        ["Msg_CheckingUpdatesAll"] = "Prüfe Updates auf allen Geräten…",
        ["Msg_UpdatesDoneSome"] = "Update-Prüfung abgeschlossen: {0} Gerät(e) mit verfügbarem Update.",
        ["Msg_UpdatesDoneNone"] = "Update-Prüfung abgeschlossen: alle Geräte aktuell (oder nicht erreichbar).",
        ["Msg_CheckingUpdateOne"] = "Prüfe Update auf {0}…",
        ["Msg_UpdateAvailableOne"] = "{0}: Update auf {1} verfügbar.",
        ["Msg_NoUpdateOne"] = "{0}: {1}",
        ["Msg_NoUpdateFallback"] = "kein Update verfügbar",
        ["Msg_SettingChannel"] = "Setze Kanal «{0}» auf {1} und prüfe Updates…",
        ["Msg_ChannelResult"] = "{0}: Kanal «{1}», {2}",
        ["Msg_ChannelUpdateAvail"] = "Update auf {0} verfügbar.",
        ["Msg_ChannelNoUpdate"] = "kein Update verfügbar.",
        ["Msg_ChannelFailed"] = "{0}: Kanalwechsel fehlgeschlagen – {1}",
        ["Msg_NoDevicesConfigured"] = "Keine Geräte konfiguriert.",
        ["Msg_SaveConfigFailed"] = "Konnte Konfiguration nicht speichern:\n{0}",

        // Backups (MainWindow)
        ["Msg_LoadingConfig"] = "Lade Konfiguration von {0}…",
        ["Msg_BackupFailed"] = "Backup von {0} fehlgeschlagen: {1}",
        ["Msg_BackupSaveTitle"] = "Config-Backup speichern",
        ["Msg_BackupCantLoad"] = "Konnte Konfiguration nicht laden:\n{0}",
        ["Msg_BackupSaved"] = "Backup von {0} gespeichert: {1}",
        ["Msg_SaveFailed"] = "Speichern fehlgeschlagen: {0}",
        ["Msg_SaveFailedTitle"] = "Config-Backup",
        ["Msg_SaveFileFailed"] = "Konnte Datei nicht speichern:\n{0}",
        ["Dlg_FolderTitle"] = "Zielordner für Config-Backups wählen",
        ["Msg_BackingUpAll"] = "Sichere Konfiguration von {0} Gerät(en)…",
        ["Msg_BackupAllDone"] = "Backups fertig: {0} gespeichert, {1} fehlgeschlagen. Ordner: {2}",
        ["Msg_BackupAllReport"] = "{0} von {1} Backups gespeichert in:\n{2}\n\nFehlgeschlagen:\n• {3}",
        ["Msg_BackupAllReportTitle"] = "Config-Backups",
        ["Dlg_RscFilter"] = "RouterOS-Export (*.rsc)|*.rsc|Textdatei (*.txt)|*.txt|Alle Dateien (*.*)|*.*",

        // Full backup (binary)
        ["Full_SaveTitle"] = "Voll-Backup (.backup) speichern",
        ["Full_Filter"] = "RouterOS-Backup (*.backup)|*.backup|Alle Dateien (*.*)|*.*",
        ["Full_Running"] = "Erstelle Voll-Backup auf {0} und lade es herunter…",
        ["Full_Saved"] = "Voll-Backup von {0} gespeichert: {1}",
        ["Full_Failed"] = "Voll-Backup von {0} fehlgeschlagen: {1}",
        ["Full_FailedTitle"] = "Voll-Backup",
        ["Full_FailedBody"] = "Voll-Backup fehlgeschlagen:\n{0}",

        // Edit/add device
        ["De_TitleAdd"] = "Gerät hinzufügen",
        ["De_TitleEdit"] = "Gerät bearbeiten",
        ["De_Name"] = "Name:",
        ["De_Address"] = "Adresse (IP/Host):",
        ["De_Connection"] = "Verbindung:",
        ["De_Https"] = "HTTPS",
        ["De_Port"] = "Port:",
        ["De_IgnoreCert"] = "Zertifikatsfehler ignorieren",
        ["De_User"] = "Benutzer:",
        ["De_Password"] = "Passwort:",
        ["De_Monitor"] = "Automatisch überwachen (Auto-Abfrage)",
        ["De_Notes"] = "Notizen:",
        ["De_PwHint"] = "Leer lassen = bisheriges Passwort behalten.",
        ["De_Test"] = "Verbindung testen",
        ["De_Ok"] = "OK",
        ["De_Cancel"] = "Abbrechen",
        ["De_Connecting"] = "Verbinde…",
        ["De_TestOk"] = "✔ Verbunden: {0} – {1}, RouterOS {2}",
        ["De_TestErr"] = "✘ Fehler: {0}",
        ["De_HttpHint"] = "\n💡 Das Gerät antwortet aber via HTTP (Port 80): Entweder den Haken bei HTTPS entfernen, oder auf dem Gerät www-ssl ein Zertifikat zuweisen (Rezept im README).",
        ["De_ErrAddressEmpty"] = "Adresse darf nicht leer sein.",
        ["De_ErrPort"] = "Ungültiger Port.",

        // Scan
        ["Sc_Title"] = "Netzwerk scannen",
        ["Sc_Mndp"] = "📡 MNDP-Discovery (MikroTik im LAN)",
        ["Sc_Subnet"] = "Subnetz:",
        ["Sc_ScanBtn"] = "🔍 Subnetz scannen",
        ["Sc_Stop"] = "⏹ Stopp",
        ["Sc_Intro"] = "MNDP findet MikroTik-Geräte per Broadcast; der Subnetz-Scan findet zusätzlich andere Geräte (Ping + Port-Check).",
        ["Sc_DefaultCreds"] = "Standard-Zugangsdaten für neue Geräte:",
        ["Sc_User"] = "Benutzer:",
        ["Sc_Password"] = "Passwort:",
        ["Sc_AddSelected"] = "Ausgewählte hinzufügen",
        ["Sc_Close"] = "Schliessen",
        ["Col_Ip"] = "IP",
        ["Col_Identity"] = "Identity",
        ["Col_Mac"] = "MAC",
        ["Col_Source"] = "Quelle",
        ["Col_Hint"] = "Hinweis",
        ["Sc_MndpRunning"] = "MNDP-Discovery läuft (5 Sekunden)…",
        ["Sc_MndpDone"] = "MNDP-Discovery abgeschlossen: {0} MikroTik-Gerät(e) gefunden.",
        ["Sc_MndpBusy"] = "MNDP nicht möglich (Port 5678 belegt? Winbox/The Dude offen?): {0}",
        ["Sc_MndpError"] = "MNDP-Fehler: {0}",
        ["Sc_Scanning"] = "Scanne {0} ({1} Adressen)…",
        ["Sc_ScanProgress"] = "Scanne {0}: {1}/{2} geprüft, {3} Gerät(e) gefunden…",
        ["Sc_ScanDone"] = "Scan abgeschlossen: {0} erreichbare(s) Gerät(e) in {1}.",
        ["Sc_ScanCancelled"] = "Scan abgebrochen.",
        ["Sc_ScanError"] = "Scan-Fehler: {0}",
        ["Sc_NoneSelected"] = "Keine Geräte ausgewählt.",
        ["Sc_HintAlreadyAdded"] = "bereits in der Geräteliste",
        ["Sc_HintLikely"] = "vermutlich MikroTik",
        ["Sc_HintPorts"] = "Ports: {0}",

        // Mass update
        ["Ua_Title"] = "Updates installieren",
        ["Ua_Warn"] = "Achtung: Jedes Update rebootet das Gerät. Die Installation läuft sequenziell in der Reihenfolge der Liste – Geräte am Netzwerkrand (APs, Switches) zuerst, den Uplink-Router zuletzt, sonst sägt man den Ast ab, auf dem die restlichen Geräte erreichbar sind. Reihenfolge mit ▲/▼ anpassen.",
        ["Ua_WaitOnline"] = "Warten bis Gerät wieder online",
        ["Ua_ContinueOnError"] = "Bei Fehler mit nächstem Gerät weiterfahren",
        ["Ua_Start"] = "▶ Start",
        ["Ua_Stop"] = "⏹ Stopp",
        ["Ua_Close"] = "Schliessen",
        ["Col_Device"] = "Gerät",
        ["Col_Installed"] = "Installiert",
        ["Col_State"] = "Stand",
        ["Ua_ConfirmBody"] = "Jetzt {0} Gerät(e) nacheinander aktualisieren?\nJedes Gerät wird dabei neu gestartet.",
        ["Ua_ConfirmTitle"] = "Updates installieren",
        ["Ua_NoneSelected"] = "Keine Geräte angehakt.",
        ["Ua_StopRequested"] = "Stopp angefordert – aktueller Schritt wird noch beendet…",
        ["Ua_CloseWhileRunning"] = "Lauf zuerst mit «Stopp» beenden.",
        ["Ua_Done"] = "— Fertig: {0} aktualisiert, {1} fehlgeschlagen. —",
        ["Ua_Stopped"] = "— Lauf gestoppt. —",
        ["Ua_AbortOnError"] = "Abbruch wegen Fehler (Option «Bei Fehler weiterfahren» ist aus).",
        ["Ua_DeviceHeader"] = "══ {0} ({1}) ══",
        ["Ua_Checking"] = "Prüfe auf Updates…",
        ["Ua_CheckFailed"] = "✘ Update-Prüfung fehlgeschlagen: {0}",
        ["Ua_AlreadyCurrent"] = "Bereits aktuell – übersprungen.",
        ["Ua_StateCheck"] = "Prüfe Update…",
        ["Ua_StateCheckFailed"] = "Prüfung fehlgeschlagen: {0}",
        ["Ua_StateCurrent"] = "bereits aktuell",
        ["Ua_StateInstalling"] = "Installiere {0}…",
        ["Ua_Installing"] = "Installiere Update auf {0} – Gerät lädt Pakete und rebootet…",
        ["Ua_InstallFailed"] = "✘ Installation fehlgeschlagen: {0}",
        ["Ua_StateInstallFailed"] = "Installation fehlgeschlagen: {0}",
        ["Ua_StateStarted"] = "Update gestartet",
        ["Ua_StartedNoWait"] = "Update gestartet (ohne Warten auf Reboot).",
        ["Ua_StateWaiting"] = "Warte auf Reboot…",
        ["Ua_StateWaitingSec"] = "Warte auf Reboot… (noch {0} s)",
        ["Ua_BackOnline"] = "✔ {0} ist wieder online, Version {1}.",
        ["Ua_StateDone"] = "✔ Fertig – Version {0}",
        ["Ua_StateTimeout"] = "✘ Nicht wieder erreichbar (Timeout)",
        ["Ua_Timeout"] = "✘ {0} war nach {1} Minuten nicht wieder erreichbar.",
        ["Ua_StateUpdateAvail"] = "Update verfügbar",

        // Settings
        ["Set_Title"] = "Einstellungen",
        ["Set_Language"] = "Sprache:",
        ["Set_LangSystem"] = "System (Windows)",
        ["Set_LangGerman"] = "Deutsch",
        ["Set_LangEnglish"] = "Englisch",
        ["Set_LangSwiss"] = "Schweizerdeutsch",
        ["Set_LangHint"] = "Sprachänderung wirkt sofort.",
        ["Set_BackupMethod"] = "Voll-Backup-Methode (.backup):",
        ["Set_BackupAuto"] = "Automatisch (Web, sonst SSH)",
        ["Set_BackupWeb"] = "Web (WebFig)",
        ["Set_BackupSsh"] = "SSH (SCP)",
        ["Set_SshPort"] = "SSH-Port:",
        ["Set_BackupInfo"] = "Das binäre .backup lässt sich nicht über die REST-API holen. «Web» spricht MikroTiks WebFig-Protokoll (wie der Browser) – derzeit noch nicht verfügbar, weicht auf SSH aus. «SSH» nutzt den ab Werk aktiven, verschlüsselten SSH-Dienst (SCP). Der reine Config-Export (.rsc) braucht nichts davon und läuft immer über HTTPS.",
        ["Set_Save"] = "Speichern",
        ["Set_Cancel"] = "Abbrechen",
    };

    public static readonly Dictionary<string, string> English = new()
    {
        // Toolbar
        ["Tb_Scan"] = "🔍 Scan…",
        ["Tb_Add"] = "➕ Add",
        ["Tb_Edit"] = "✏️ Edit",
        ["Tb_Remove"] = "🗑️ Remove",
        ["Tb_RefreshAll"] = "🔄 Refresh all",
        ["Tb_BackupAll"] = "💾 Save backups…",
        ["Tb_CheckUpdates"] = "📦 Check updates",
        ["Tb_InstallUpdates"] = "⬆️ Install updates…",
        ["Tb_Settings"] = "⚙️ Settings…",
        ["Tb_AutoRefresh"] = "Auto-refresh every",

        // Device table
        ["Col_Name"] = "Name",
        ["Col_Address"] = "Address",
        ["Col_Board"] = "Board",
        ["Col_Version"] = "Version",
        ["Col_Latest"] = "Latest",
        ["Col_Cpu"] = "CPU",
        ["Col_Ram"] = "RAM",
        ["Col_Uptime"] = "Uptime",
        ["Col_LastError"] = "Last error",

        // Tabs
        ["Tab_Logs"] = "Logs",
        ["Tab_Monitoring"] = "CPU / memory load",
        ["Tab_Update"] = "Update",
        ["Tab_Details"] = "Details",

        // Logs
        ["Logs_Load"] = "🔄 Refresh logs",
        ["Logs_Count"] = "Count:",
        ["Logs_All"] = "all",
        ["Logs_Filter"] = "Filter:",
        ["Col_Time"] = "Time",
        ["Col_Topics"] = "Topics",
        ["Col_Message"] = "Message",

        // Monitoring
        ["Chart_NoData"] = "No samples yet – the device is recorded on the next refresh.",
        ["Col_Protocol"] = "Protocol",
        ["Sc_Clear"] = "🗑️ Clear",
        ["Sc_CredsHint"] = "New devices use the default credentials from Settings.",
        ["Set_DefaultPwHint"] = "Leave empty to keep the current password.",

        // Device status / short update status
        ["St_Online"] = "Online",
        ["St_Offline"] = "Offline",
        ["St_Busy"] = "Busy…",
        ["St_Unknown"] = "Unknown",
        ["Upd_CheckFailedStatus"] = "Check failed",
        ["Upd_ChannelFailedStatus"] = "Channel switch failed",

        // Update tab
        ["Upd_Installed"] = "Installed version:",
        ["Upd_Latest"] = "Latest version:",
        ["Upd_Channel"] = "Channel:",
        ["Upd_Status"] = "Status:",
        ["Upd_ChannelLabel"] = "Update channel:",
        ["Upd_ChannelHint"] = "Selection is applied and checked immediately.",
        ["Upd_Check"] = "Check update",
        ["Upd_Install"] = "Install update (reboots!)",
        ["Upd_Note"] = "Note: A RouterOS update downloads the packages and reboots the device. For several devices use the «Install updates…» assistant in the toolbar – it installs sequentially and waits until each device is back online.",
        ["Upd_RightsBox"] = "Required permissions of the API user:\n• Monitoring/logs/checking updates only: read, rest-api\n• Switch channel & install update: additionally write, reboot, test\n• Config backup (.rsc): via HTTPS with write (temporary export file) – no FTP needed\n• Full backup (.backup) via SSH: additionally ssh, ftp (SSH service enabled)",

        // Details tab
        ["Det_Connection"] = "Connection:",
        ["Det_User"] = "User:",
        ["Det_Mac"] = "MAC:",
        ["Det_Notes"] = "Notes:",
        ["Det_Edit"] = "✏️ Edit device…",
        ["Det_BackupRsc"] = "💾 Config backup (.rsc)…",
        ["Det_BackupFull"] = "🗄️ Full backup (.backup)…",
        ["Det_BackupDesc"] = "Config backup (.rsc): complete, readable configuration over HTTPS – without passwords/keys, ideal for versioning, restorable with /import. Full backup (.backup): exact binary copy incl. passwords; downloaded via Web/WebFig or SSH depending on settings (not possible through the REST API).",

        // Status bar / messages (MainWindow)
        ["Status_Ready"] = "Ready",
        ["Msg_NoDevices"] = "No devices configured – use «Scan…» to search the network or click «Add».",
        ["Msg_SelectDeviceFirst"] = "Select a device first.",
        ["Msg_Querying"] = "Querying {0} device(s)…",
        ["Msg_OnlineSummary"] = "{0} – {1}/{2} devices online",
        ["Msg_UpdatesAvailableSuffix"] = ", {0} update(s) available",
        ["Msg_DevicesAdded"] = "{0} device(s) added.",
        ["Msg_RemoveConfirm"] = "Really remove «{0}» ({1}) from monitoring?\nNothing is changed on the device itself.",
        ["Msg_RemoveTitle"] = "Remove device",
        ["Msg_LoadingLogs"] = "Loading logs from {0}…",
        ["Msg_LogsLoaded"] = "Loaded {0} log entries from {1}.",
        ["Msg_LogsFailed"] = "Could not load logs from {0}: {1}",
        ["Msg_CheckingUpdatesAll"] = "Checking updates on all devices…",
        ["Msg_UpdatesDoneSome"] = "Update check finished: {0} device(s) with an available update.",
        ["Msg_UpdatesDoneNone"] = "Update check finished: all devices up to date (or unreachable).",
        ["Msg_CheckingUpdateOne"] = "Checking update on {0}…",
        ["Msg_UpdateAvailableOne"] = "{0}: update to {1} available.",
        ["Msg_NoUpdateOne"] = "{0}: {1}",
        ["Msg_NoUpdateFallback"] = "no update available",
        ["Msg_SettingChannel"] = "Setting channel «{0}» on {1} and checking updates…",
        ["Msg_ChannelResult"] = "{0}: channel «{1}», {2}",
        ["Msg_ChannelUpdateAvail"] = "update to {0} available.",
        ["Msg_ChannelNoUpdate"] = "no update available.",
        ["Msg_ChannelFailed"] = "{0}: channel switch failed – {1}",
        ["Msg_NoDevicesConfigured"] = "No devices configured.",
        ["Msg_SaveConfigFailed"] = "Could not save configuration:\n{0}",

        // Backups (MainWindow)
        ["Msg_LoadingConfig"] = "Loading configuration from {0}…",
        ["Msg_BackupFailed"] = "Backup of {0} failed: {1}",
        ["Msg_BackupSaveTitle"] = "Save config backup",
        ["Msg_BackupCantLoad"] = "Could not load configuration:\n{0}",
        ["Msg_BackupSaved"] = "Backup of {0} saved: {1}",
        ["Msg_SaveFailed"] = "Saving failed: {0}",
        ["Msg_SaveFailedTitle"] = "Config backup",
        ["Msg_SaveFileFailed"] = "Could not save file:\n{0}",
        ["Dlg_FolderTitle"] = "Choose target folder for config backups",
        ["Msg_BackingUpAll"] = "Backing up configuration of {0} device(s)…",
        ["Msg_BackupAllDone"] = "Backups done: {0} saved, {1} failed. Folder: {2}",
        ["Msg_BackupAllReport"] = "{0} of {1} backups saved to:\n{2}\n\nFailed:\n• {3}",
        ["Msg_BackupAllReportTitle"] = "Config backups",
        ["Dlg_RscFilter"] = "RouterOS export (*.rsc)|*.rsc|Text file (*.txt)|*.txt|All files (*.*)|*.*",

        // Full backup (binary)
        ["Full_SaveTitle"] = "Save full backup (.backup)",
        ["Full_Filter"] = "RouterOS backup (*.backup)|*.backup|All files (*.*)|*.*",
        ["Full_Running"] = "Creating full backup on {0} and downloading it…",
        ["Full_Saved"] = "Full backup of {0} saved: {1}",
        ["Full_Failed"] = "Full backup of {0} failed: {1}",
        ["Full_FailedTitle"] = "Full backup",
        ["Full_FailedBody"] = "Full backup failed:\n{0}",

        // Edit/add device
        ["De_TitleAdd"] = "Add device",
        ["De_TitleEdit"] = "Edit device",
        ["De_Name"] = "Name:",
        ["De_Address"] = "Address (IP/host):",
        ["De_Connection"] = "Connection:",
        ["De_Https"] = "HTTPS",
        ["De_Port"] = "Port:",
        ["De_IgnoreCert"] = "Ignore certificate errors",
        ["De_User"] = "User:",
        ["De_Password"] = "Password:",
        ["De_Monitor"] = "Monitor automatically (auto-refresh)",
        ["De_Notes"] = "Notes:",
        ["De_PwHint"] = "Leave empty = keep current password.",
        ["De_Test"] = "Test connection",
        ["De_Ok"] = "OK",
        ["De_Cancel"] = "Cancel",
        ["De_Connecting"] = "Connecting…",
        ["De_TestOk"] = "✔ Connected: {0} – {1}, RouterOS {2}",
        ["De_TestErr"] = "✘ Error: {0}",
        ["De_HttpHint"] = "\n💡 The device does answer via HTTP (port 80): either untick HTTPS, or assign a certificate to www-ssl on the device (recipe in the README).",
        ["De_ErrAddressEmpty"] = "Address must not be empty.",
        ["De_ErrPort"] = "Invalid port.",

        // Scan
        ["Sc_Title"] = "Scan network",
        ["Sc_Mndp"] = "📡 MNDP discovery (MikroTik on LAN)",
        ["Sc_Subnet"] = "Subnet:",
        ["Sc_ScanBtn"] = "🔍 Scan subnet",
        ["Sc_Stop"] = "⏹ Stop",
        ["Sc_Intro"] = "MNDP finds MikroTik devices via broadcast; the subnet scan also finds other devices (ping + port check).",
        ["Sc_DefaultCreds"] = "Default credentials for new devices:",
        ["Sc_User"] = "User:",
        ["Sc_Password"] = "Password:",
        ["Sc_AddSelected"] = "Add selected",
        ["Sc_Close"] = "Close",
        ["Col_Ip"] = "IP",
        ["Col_Identity"] = "Identity",
        ["Col_Mac"] = "MAC",
        ["Col_Source"] = "Source",
        ["Col_Hint"] = "Hint",
        ["Sc_MndpRunning"] = "MNDP discovery running (5 seconds)…",
        ["Sc_MndpDone"] = "MNDP discovery finished: {0} MikroTik device(s) found.",
        ["Sc_MndpBusy"] = "MNDP not possible (port 5678 in use? Winbox/The Dude open?): {0}",
        ["Sc_MndpError"] = "MNDP error: {0}",
        ["Sc_Scanning"] = "Scanning {0} ({1} addresses)…",
        ["Sc_ScanProgress"] = "Scanning {0}: {1}/{2} checked, {3} device(s) found…",
        ["Sc_ScanDone"] = "Scan finished: {0} reachable device(s) in {1}.",
        ["Sc_ScanCancelled"] = "Scan cancelled.",
        ["Sc_ScanError"] = "Scan error: {0}",
        ["Sc_NoneSelected"] = "No devices selected.",
        ["Sc_HintAlreadyAdded"] = "already in device list",
        ["Sc_HintLikely"] = "probably MikroTik",
        ["Sc_HintPorts"] = "Ports: {0}",

        // Mass update
        ["Ua_Title"] = "Install updates",
        ["Ua_Warn"] = "Warning: Every update reboots the device. Installation runs sequentially in list order – edge devices (APs, switches) first, the uplink router last, otherwise you cut off the branch the remaining devices hang on. Reorder with ▲/▼.",
        ["Ua_WaitOnline"] = "Wait until device is back online",
        ["Ua_ContinueOnError"] = "Continue with next device on error",
        ["Ua_Start"] = "▶ Start",
        ["Ua_Stop"] = "⏹ Stop",
        ["Ua_Close"] = "Close",
        ["Col_Device"] = "Device",
        ["Col_Installed"] = "Installed",
        ["Col_State"] = "State",
        ["Ua_ConfirmBody"] = "Update {0} device(s) one after another now?\nEach device will be rebooted.",
        ["Ua_ConfirmTitle"] = "Install updates",
        ["Ua_NoneSelected"] = "No devices ticked.",
        ["Ua_StopRequested"] = "Stop requested – finishing the current step…",
        ["Ua_CloseWhileRunning"] = "Stop the run with «Stop» first.",
        ["Ua_Done"] = "— Done: {0} updated, {1} failed. —",
        ["Ua_Stopped"] = "— Run stopped. —",
        ["Ua_AbortOnError"] = "Aborting due to error (option «Continue on error» is off).",
        ["Ua_DeviceHeader"] = "══ {0} ({1}) ══",
        ["Ua_Checking"] = "Checking for updates…",
        ["Ua_CheckFailed"] = "✘ Update check failed: {0}",
        ["Ua_AlreadyCurrent"] = "Already up to date – skipped.",
        ["Ua_StateCheck"] = "Checking update…",
        ["Ua_StateCheckFailed"] = "Check failed: {0}",
        ["Ua_StateCurrent"] = "already up to date",
        ["Ua_StateInstalling"] = "Installing {0}…",
        ["Ua_Installing"] = "Installing update to {0} – device downloads packages and reboots…",
        ["Ua_InstallFailed"] = "✘ Installation failed: {0}",
        ["Ua_StateInstallFailed"] = "Installation failed: {0}",
        ["Ua_StateStarted"] = "Update started",
        ["Ua_StartedNoWait"] = "Update started (without waiting for reboot).",
        ["Ua_StateWaiting"] = "Waiting for reboot…",
        ["Ua_StateWaitingSec"] = "Waiting for reboot… ({0} s left)",
        ["Ua_BackOnline"] = "✔ {0} is back online, version {1}.",
        ["Ua_StateDone"] = "✔ Done – version {0}",
        ["Ua_StateTimeout"] = "✘ Not reachable again (timeout)",
        ["Ua_Timeout"] = "✘ {0} was not reachable again after {1} minutes.",
        ["Ua_StateUpdateAvail"] = "Update available",

        // Settings
        ["Set_Title"] = "Settings",
        ["Set_Language"] = "Language:",
        ["Set_LangSystem"] = "System (Windows)",
        ["Set_LangGerman"] = "German",
        ["Set_LangEnglish"] = "English",
        ["Set_LangSwiss"] = "Swiss German",
        ["Set_LangHint"] = "Language change takes effect immediately.",
        ["Set_BackupMethod"] = "Full backup method (.backup):",
        ["Set_BackupAuto"] = "Automatic (web, else SSH)",
        ["Set_BackupWeb"] = "Web (WebFig)",
        ["Set_BackupSsh"] = "SSH (SCP)",
        ["Set_SshPort"] = "SSH port:",
        ["Set_BackupInfo"] = "The binary .backup cannot be fetched through the REST API. «Web» speaks MikroTik's WebFig protocol (like the browser) – currently not yet available, falls back to SSH. «SSH» uses the factory-enabled, encrypted SSH service (SCP). The plain config export (.rsc) needs none of this and always runs over HTTPS.",
        ["Set_Save"] = "Save",
        ["Set_Cancel"] = "Cancel",
    };

    // Swiss German (Zurich-leaning, no official spelling)
    public static readonly Dictionary<string, string> SwissGerman = new()
    {
        // Toolbar
        ["Tb_Scan"] = "🔍 Scanne…",
        ["Tb_Add"] = "➕ Dezuätue",
        ["Tb_Edit"] = "✏️ Bearbeite",
        ["Tb_Remove"] = "🗑️ Ewägtue",
        ["Tb_RefreshAll"] = "🔄 Alli abfrage",
        ["Tb_BackupAll"] = "💾 Backups sichere…",
        ["Tb_CheckUpdates"] = "📦 Updates prüefe",
        ["Tb_InstallUpdates"] = "⬆️ Updates installiere…",
        ["Tb_Settings"] = "⚙️ Iistellige…",
        ["Tb_AutoRefresh"] = "Auto-Abfrag alli",

        // Device table
        ["Col_Name"] = "Name",
        ["Col_Address"] = "Adrässe",
        ["Col_Board"] = "Board",
        ["Col_Version"] = "Version",
        ["Col_Latest"] = "Nöischti",
        ["Col_Cpu"] = "CPU",
        ["Col_Ram"] = "RAM",
        ["Col_Uptime"] = "Uptime",
        ["Col_LastError"] = "Letschtä Fähler",

        // Tabs
        ["Tab_Logs"] = "Logs",
        ["Tab_Monitoring"] = "CPU / RAM-Lascht",
        ["Tab_Update"] = "Update",
        ["Tab_Details"] = "Details",

        // Logs
        ["Logs_Load"] = "🔄 Logs aktualisiere",
        ["Logs_Count"] = "Aazahl:",
        ["Logs_All"] = "alli",
        ["Logs_Filter"] = "Filter:",
        ["Col_Time"] = "Ziit",
        ["Col_Topics"] = "Topics",
        ["Col_Message"] = "Mäldig",

        // Monitoring
        ["Chart_NoData"] = "Na kei Mässwärt – s Grät wird bim nächschtä Abfrage erfasst.",
        ["Col_Protocol"] = "Protokoll",
        ["Sc_Clear"] = "🗑️ Lääre",
        ["Sc_CredsHint"] = "Nöii Grät bruuched d Standard-Zugangsdatä us de Iistellige.",
        ["Set_DefaultPwHint"] = "Läär lah = aktuells Passwort behalte.",

        // Grätstatus / churzi Update-Status
        ["St_Online"] = "Online",
        ["St_Offline"] = "Offline",
        ["St_Busy"] = "Bschäftiget…",
        ["St_Unknown"] = "Unbekannt",
        ["Upd_CheckFailedStatus"] = "Prüefig fählgschlage",
        ["Upd_ChannelFailedStatus"] = "Kanalwächsel fählgschlage",

        // Update tab
        ["Upd_Installed"] = "Installierti Version:",
        ["Upd_Latest"] = "Nöischti Version:",
        ["Upd_Channel"] = "Kanal:",
        ["Upd_Status"] = "Status:",
        ["Upd_ChannelLabel"] = "Update-Kanal:",
        ["Upd_ChannelHint"] = "D Uswahl wird sofort gsetzt und prüeft.",
        ["Upd_Check"] = "Update prüefe",
        ["Upd_Install"] = "Update installiere (rebootet!)",
        ["Upd_Note"] = "Hiiwiis: Es RouterOS-Update ladt d Päckli abä und startet s Grät neu. Für mehreri Grät de Assischtänt «Updates installiere…» i de Wärchzüügleischtä bruuche – dört wird sequenziell installiert und gwartet, bis jedes Grät wieder online isch.",
        ["Upd_RightsBox"] = "Nötigi Rächt vom API-Benutzer:\n• Nur Überwache/Logs/Update prüefe: read, rest-api\n• Kanal wächsle & Update installiere: zusätzlich write, reboot, test\n• Config-Backup (.rsc): über HTTPS mit write (temporäri Exportdatei) – kei FTP nötig\n• Voll-Backup (.backup) via SSH: zusätzlich ssh, ftp (SSH-Dienscht aktiv)",

        // Details tab
        ["Det_Connection"] = "Verbindig:",
        ["Det_User"] = "Benutzer:",
        ["Det_Mac"] = "MAC:",
        ["Det_Notes"] = "Notizä:",
        ["Det_Edit"] = "✏️ Grät bearbeite…",
        ["Det_BackupRsc"] = "💾 Config-Backup (.rsc)…",
        ["Det_BackupFull"] = "🗄️ Voll-Backup (.backup)…",
        ["Det_BackupDesc"] = "Config-Backup (.rsc): vollständigi, läsbari Konfiguration über HTTPS – ohni Passwörter/Keys, ideal zum Versioniere, mit /import wiederherstellbar. Voll-Backup (.backup): exakti Binärkopie inkl. Passwörter; Download je nach Iistellig über Web/WebFig oder SSH (nöd über d REST-API möglich).",

        // Status bar / messages
        ["Status_Ready"] = "Parat",
        ["Msg_NoDevices"] = "Kei Grät konfiguriert – mit «Scanne…» s Netzwärk duresuäche oder «Dezuätue» klicke.",
        ["Msg_SelectDeviceFirst"] = "Zerscht es Grät uswähle.",
        ["Msg_Querying"] = "Frag {0} Grät ab…",
        ["Msg_OnlineSummary"] = "{0} – {1}/{2} Grät online",
        ["Msg_UpdatesAvailableSuffix"] = ", {0} Update(s) verfüegbar",
        ["Msg_DevicesAdded"] = "{0} Grät dezuätah.",
        ["Msg_RemoveConfirm"] = "«{0}» ({1}) würkli us de Überwachig ewägtue?\nAm Grät sälber wird nüt gänderet.",
        ["Msg_RemoveTitle"] = "Grät ewägtue",
        ["Msg_LoadingLogs"] = "Lade Logs vo {0}…",
        ["Msg_LogsLoaded"] = "{0} Logiiträg vo {1} glade.",
        ["Msg_LogsFailed"] = "Logs vo {0} händ nöd chönä glade werde: {1}",
        ["Msg_CheckingUpdatesAll"] = "Prüefe Updates uf allnä Grät…",
        ["Msg_UpdatesDoneSome"] = "Update-Prüefig fertig: {0} Grät mit verfüegbarem Update.",
        ["Msg_UpdatesDoneNone"] = "Update-Prüefig fertig: alli Grät aktuell (oder nöd erreichbar).",
        ["Msg_CheckingUpdateOne"] = "Prüefe Update uf {0}…",
        ["Msg_UpdateAvailableOne"] = "{0}: Update uf {1} verfüegbar.",
        ["Msg_NoUpdateOne"] = "{0}: {1}",
        ["Msg_NoUpdateFallback"] = "kei Update verfüegbar",
        ["Msg_SettingChannel"] = "Setze Kanal «{0}» uf {1} und prüefe Updates…",
        ["Msg_ChannelResult"] = "{0}: Kanal «{1}», {2}",
        ["Msg_ChannelUpdateAvail"] = "Update uf {0} verfüegbar.",
        ["Msg_ChannelNoUpdate"] = "kei Update verfüegbar.",
        ["Msg_ChannelFailed"] = "{0}: Kanalwächsel fählgschlage – {1}",
        ["Msg_NoDevicesConfigured"] = "Kei Grät konfiguriert.",
        ["Msg_SaveConfigFailed"] = "Ha d Konfiguration nöd chönä speichere:\n{0}",

        // Backups
        ["Msg_LoadingConfig"] = "Lade Konfiguration vo {0}…",
        ["Msg_BackupFailed"] = "Backup vo {0} fählgschlage: {1}",
        ["Msg_BackupSaveTitle"] = "Config-Backup speichere",
        ["Msg_BackupCantLoad"] = "Ha d Konfiguration nöd chönä lade:\n{0}",
        ["Msg_BackupSaved"] = "Backup vo {0} gspeicheret: {1}",
        ["Msg_SaveFailed"] = "Speichere fählgschlage: {0}",
        ["Msg_SaveFailedTitle"] = "Config-Backup",
        ["Msg_SaveFileFailed"] = "Ha d Datei nöd chönä speichere:\n{0}",
        ["Dlg_FolderTitle"] = "Zielordner für Config-Backups wähle",
        ["Msg_BackingUpAll"] = "Sichere Konfiguration vo {0} Grät…",
        ["Msg_BackupAllDone"] = "Backups fertig: {0} gspeicheret, {1} fählgschlage. Ordner: {2}",
        ["Msg_BackupAllReport"] = "{0} vo {1} Backups gspeicheret i:\n{2}\n\nFählgschlage:\n• {3}",
        ["Msg_BackupAllReportTitle"] = "Config-Backups",
        ["Dlg_RscFilter"] = "RouterOS-Export (*.rsc)|*.rsc|Textdatei (*.txt)|*.txt|Alli Dateiä (*.*)|*.*",

        // Full backup (binary)
        ["Full_SaveTitle"] = "Voll-Backup (.backup) speichere",
        ["Full_Filter"] = "RouterOS-Backup (*.backup)|*.backup|Alli Dateiä (*.*)|*.*",
        ["Full_Running"] = "Erstelle Voll-Backup uf {0} und lade s abä…",
        ["Full_Saved"] = "Voll-Backup vo {0} gspeicheret: {1}",
        ["Full_Failed"] = "Voll-Backup vo {0} fählgschlage: {1}",
        ["Full_FailedTitle"] = "Voll-Backup",
        ["Full_FailedBody"] = "Voll-Backup fählgschlage:\n{0}",

        // Edit/add device
        ["De_TitleAdd"] = "Grät dezuätue",
        ["De_TitleEdit"] = "Grät bearbeite",
        ["De_Name"] = "Name:",
        ["De_Address"] = "Adrässe (IP/Host):",
        ["De_Connection"] = "Verbindig:",
        ["De_Https"] = "HTTPS",
        ["De_Port"] = "Port:",
        ["De_IgnoreCert"] = "Zertifikatsfähler ignoriere",
        ["De_User"] = "Benutzer:",
        ["De_Password"] = "Passwort:",
        ["De_Monitor"] = "Automatisch überwache (Auto-Abfrag)",
        ["De_Notes"] = "Notizä:",
        ["De_PwHint"] = "Läär lah = bisherigs Passwort behalte.",
        ["De_Test"] = "Verbindig teste",
        ["De_Ok"] = "OK",
        ["De_Cancel"] = "Abbräche",
        ["De_Connecting"] = "Verbinde…",
        ["De_TestOk"] = "✔ Verbunde: {0} – {1}, RouterOS {2}",
        ["De_TestErr"] = "✘ Fähler: {0}",
        ["De_HttpHint"] = "\n💡 S Grät antwortet aber via HTTP (Port 80): Entweder de Haggä bi HTTPS ewägtue, oder am Grät em www-ssl es Zertifikat zuewiise (Rezäpt im README).",
        ["De_ErrAddressEmpty"] = "D Adrässe dörf nöd läär sii.",
        ["De_ErrPort"] = "Ungültigä Port.",

        // Scan
        ["Sc_Title"] = "Netzwärk scanne",
        ["Sc_Mndp"] = "📡 MNDP-Discovery (MikroTik im LAN)",
        ["Sc_Subnet"] = "Subnetz:",
        ["Sc_ScanBtn"] = "🔍 Subnetz scanne",
        ["Sc_Stop"] = "⏹ Stopp",
        ["Sc_Intro"] = "MNDP findet MikroTik-Grät per Broadcast; de Subnetz-Scan findet zusätzlich anderi Grät (Ping + Port-Check).",
        ["Sc_DefaultCreds"] = "Standard-Zugangsdatä für nöii Grät:",
        ["Sc_User"] = "Benutzer:",
        ["Sc_Password"] = "Passwort:",
        ["Sc_AddSelected"] = "Uswählti dezuätue",
        ["Sc_Close"] = "Zuemache",
        ["Col_Ip"] = "IP",
        ["Col_Identity"] = "Identity",
        ["Col_Mac"] = "MAC",
        ["Col_Source"] = "Quelle",
        ["Col_Hint"] = "Hiiwiis",
        ["Sc_MndpRunning"] = "MNDP-Discovery lauft (5 Sekundä)…",
        ["Sc_MndpDone"] = "MNDP-Discovery fertig: {0} MikroTik-Grät gfunde.",
        ["Sc_MndpBusy"] = "MNDP nöd möglich (Port 5678 blegt? Winbox/The Dude offe?): {0}",
        ["Sc_MndpError"] = "MNDP-Fähler: {0}",
        ["Sc_Scanning"] = "Scanne {0} ({1} Adrässe)…",
        ["Sc_ScanProgress"] = "Scanne {0}: {1}/{2} prüeft, {3} Grät gfunde…",
        ["Sc_ScanDone"] = "Scan fertig: {0} erreichbari Grät i {1}.",
        ["Sc_ScanCancelled"] = "Scan abbroche.",
        ["Sc_ScanError"] = "Scan-Fähler: {0}",
        ["Sc_NoneSelected"] = "Kei Grät uswählt.",
        ["Sc_HintAlreadyAdded"] = "scho i de Grätlischtä",
        ["Sc_HintLikely"] = "vermuetlich MikroTik",
        ["Sc_HintPorts"] = "Ports: {0}",

        // Mass update
        ["Ua_Title"] = "Updates installiere",
        ["Ua_Warn"] = "Achtung: Jedes Update rebootet s Grät. D Installation lauft sequenziell i de Reihefolg vo de Lischtä – Grät am Netzwärkrand (APs, Switches) zerscht, de Uplink-Router zletscht, susch sägt mä de Ascht ab, wo di andere Grät dra hanged. Reihefolg mit ▲/▼ apasse.",
        ["Ua_WaitOnline"] = "Warte bis s Grät wieder online isch",
        ["Ua_ContinueOnError"] = "Bi Fähler mit em nächschtä Grät wiiterfahre",
        ["Ua_Start"] = "▶ Start",
        ["Ua_Stop"] = "⏹ Stopp",
        ["Ua_Close"] = "Zuemache",
        ["Col_Device"] = "Grät",
        ["Col_Installed"] = "Installiert",
        ["Col_State"] = "Stand",
        ["Ua_ConfirmBody"] = "Jetzt {0} Grät nachenand aktualisiere?\nJedes Grät wird debii neu gstartet.",
        ["Ua_ConfirmTitle"] = "Updates installiere",
        ["Ua_NoneSelected"] = "Kei Grät ahghäcklet.",
        ["Ua_StopRequested"] = "Stopp aagforderet – de aktuell Schritt wird na fertig gmacht…",
        ["Ua_CloseWhileRunning"] = "De Lauf zerscht mit «Stopp» beände.",
        ["Ua_Done"] = "— Fertig: {0} aktualisiert, {1} fählgschlage. —",
        ["Ua_Stopped"] = "— Lauf gstoppt. —",
        ["Ua_AbortOnError"] = "Abbruch wäge Fähler (Option «Bi Fähler wiiterfahre» isch us).",
        ["Ua_DeviceHeader"] = "══ {0} ({1}) ══",
        ["Ua_Checking"] = "Prüefe uf Updates…",
        ["Ua_CheckFailed"] = "✘ Update-Prüefig fählgschlage: {0}",
        ["Ua_AlreadyCurrent"] = "Scho aktuell – übersprunge.",
        ["Ua_StateCheck"] = "Prüefe Update…",
        ["Ua_StateCheckFailed"] = "Prüefig fählgschlage: {0}",
        ["Ua_StateCurrent"] = "scho aktuell",
        ["Ua_StateInstalling"] = "Installiere {0}…",
        ["Ua_Installing"] = "Installiere Update uf {0} – s Grät ladt Päckli und rebootet…",
        ["Ua_InstallFailed"] = "✘ Installation fählgschlage: {0}",
        ["Ua_StateInstallFailed"] = "Installation fählgschlage: {0}",
        ["Ua_StateStarted"] = "Update gstartet",
        ["Ua_StartedNoWait"] = "Update gstartet (ohni uf Reboot z'warte).",
        ["Ua_StateWaiting"] = "Warte uf Reboot…",
        ["Ua_StateWaitingSec"] = "Warte uf Reboot… (na {0} s)",
        ["Ua_BackOnline"] = "✔ {0} isch wieder online, Version {1}.",
        ["Ua_StateDone"] = "✔ Fertig – Version {0}",
        ["Ua_StateTimeout"] = "✘ Nöd wieder erreichbar (Timeout)",
        ["Ua_Timeout"] = "✘ {0} isch nach {1} Minutä nöd wieder erreichbar gsii.",
        ["Ua_StateUpdateAvail"] = "Update verfüegbar",

        // Settings
        ["Set_Title"] = "Iistellige",
        ["Set_Language"] = "Sprach:",
        ["Set_LangSystem"] = "System (Windows)",
        ["Set_LangGerman"] = "Dütsch",
        ["Set_LangEnglish"] = "Änglisch",
        ["Set_LangSwiss"] = "Schwiizerdütsch",
        ["Set_LangHint"] = "D Sprachänderig wirkt sofort.",
        ["Set_BackupMethod"] = "Voll-Backup-Methode (.backup):",
        ["Set_BackupAuto"] = "Automatisch (Web, susch SSH)",
        ["Set_BackupWeb"] = "Web (WebFig)",
        ["Set_BackupSsh"] = "SSH (SCP)",
        ["Set_SshPort"] = "SSH-Port:",
        ["Set_BackupInfo"] = "S binäri .backup chan mä nöd über d REST-API hole. «Web» redt MikroTiks WebFig-Protokoll (wiä de Browser) – zurzit na nöd verfüegbar, wiicht uf SSH us. «SSH» bruucht de ab Werk aktiv, verschlüsslet SSH-Dienscht (SCP). De reini Config-Export (.rsc) bruucht nüt devo und lauft immer über HTTPS.",
        ["Set_Save"] = "Speichere",
        ["Set_Cancel"] = "Abbräche",
    };
}
