using System.Collections.Generic;

namespace TikMan.App.Localization;

/// <summary>Translation tables. Both dictionaries must have the same keys.
/// Placeholders {0}, {1} … are filled via LocalizationManager.T(key, args).</summary>
internal static class Strings
{
    public static readonly Dictionary<string, string> German = new()
    {
        // Toolbar
        ["Tb_Scan"] = "🔍 Scannen…",
        ["Tb_Add"] = "➕ Hinzufügen",
        ["Tb_Edit"] = "✏️ Bearbeiten",
        ["Tb_Remove"] = "🗑️ Entfernen",
        ["Tb_RefreshAll"] = "🔄 Alle abfragen",
        ["Tb_BackupAll"] = "💾 Backups sichern…",
        ["Tb_CheckUpdates"] = "📦 Updates prüfen",
        ["Tb_InstallUpdates"] = "⬆️ Updates installieren…",
        ["Tb_Settings"] = "⚙️ Einstellungen…",
        ["Tb_AutoRefresh"] = "Auto-Abfrage alle",

        // Device table
        ["Col_Name"] = "Name",
        ["Col_Address"] = "Adresse",
        ["Col_Board"] = "Modell",
        ["Col_Version"] = "Version",
        ["Col_Latest"] = "Neuste",
        ["Col_Cpu"] = "CPU",
        ["Col_Ram"] = "RAM",
        ["Col_Uptime"] = "Uptime",
        ["Col_LastError"] = "Letzter Fehler",

        // Tabs
        ["Tab_Logs"] = "Logs",
        ["Tab_Monitoring"] = "CPU / RAM-Auslastung",
        ["Tab_Update"] = "Update",
        ["Tab_Details"] = "Details",

        // Logs
        ["Logs_Load"] = "🔄 Logs aktualisieren",
        ["Logs_Auto"] = "Auto (3 s)",
        ["Filter_Tip"] = "Filtert die Liste – alle eingegebenen Wörter müssen im Eintrag vorkommen.",
        ["View_Tip"] = "IPv4- und IPv6-Adresse desselben Geräts in einer Zeile zusammenfassen.",
        ["View_Combine"] = "IPv4/IPv6 zusammenfassen",
        ["Logs_Count"] = "Anzahl:",
        ["Logs_All"] = "alle",
        ["Logs_Filter"] = "Filter:",
        ["Col_Time"] = "Zeit",
        ["Col_Topics"] = "Topics",
        ["Col_Message"] = "Meldung",

        // Monitoring
        ["Chart_NoData"] = "Noch keine Messwerte – Gerät wird beim nächsten Abfragen erfasst.",
        ["Col_MarkAllTip"] = "Alle aus-/abwählen",
        ["Msg_NoDevicesMarked"] = "Keine Geräte markiert – Geräte in der Liste ankreuzen.",
        ["Msg_HttpFallbackTitle"] = "HTTP versuchen?",
        ["Col_InstalledRel"] = "Installiert (Rel.)",
        ["Col_UpdateRel"] = "Update (Rel.)",
        ["Msg_HttpFallbackPrompt"] = "{0} Gerät(e) konnten sich nicht per HTTPS verbinden.\n\nStattdessen HTTP versuchen?\n\nWARNUNG: Zugangsdaten und Daten werden dann im Klartext übertragen – nur in einem vertrauenswürdigen Netz verwenden.",
        ["Col_Vendor"] = "Hersteller",
        ["Col_MacVendor"] = "MAC-Hersteller",
        ["Col_Protocol"] = "Unterstützte Protokolle",
        ["Sc_Clear"] = "🗑️ Leeren",
        ["Sc_CredsHint"] = "Neue Geräte verwenden die Standard-Zugangsdaten aus den Einstellungen.",
        ["Set_DefaultPwHint"] = "Leer lassen = aktuelles Passwort behalten.",

        // Gerätestatus / kurze Update-Status
        ["St_Online"] = "Online",
        ["St_Offline"] = "Offline",
        ["St_Busy"] = "Beschäftigt…",
        ["St_Unknown"] = "Unbekannt",
        ["Upd_CheckFailedStatus"] = "Prüfung fehlgeschlagen",
        ["Upd_ChannelFailedStatus"] = "Kanalwechsel fehlgeschlagen",

        // Update tab
        ["Upd_Installed"] = "Installierte Version:",
        ["Upd_Latest"] = "Neuste Version:",
        ["Upd_Channel"] = "Kanal:",
        ["Upd_Status"] = "Status:",
        ["Upd_ChannelLabel"] = "Update-Kanal:",
        ["Upd_ChannelHint"] = "Auswahl wird sofort gesetzt und geprüft.",
        ["Upd_Check"] = "Update prüfen",
        ["Upd_Install"] = "Update installieren (rebootet!)",
        ["Upd_Note"] = "Hinweis: Ein RouterOS-Update lädt die Pakete herunter und startet das Gerät neu. Für mehrere Geräte den Assistenten «Updates installieren…» in der Werkzeugleiste verwenden – dort wird sequenziell installiert und gewartet, bis jedes Gerät wieder online ist.",
        ["Upd_RightsBox"] = "Benötigte Rechte des API-Benutzers:\n• Nur Überwachen/Logs/Update prüfen: read, rest-api\n• Kanal wechseln & Update installieren: zusätzlich write, reboot, test\n• Config-Backup (.rsc): über HTTPS mit write (temporäre Exportdatei) – kein FTP nötig\n• Voll-Backup (.backup) via SSH: zusätzlich ssh, ftp (SSH-Dienst aktiv)",

        // Details tab
        ["Det_Connection"] = "Verbindung:",
        ["Det_User"] = "Benutzer:",
        ["Det_Mac"] = "MAC:",
        ["Det_Notes"] = "Notizen:",
        ["Det_Edit"] = "✏️ Gerät bearbeiten…",
        ["Det_BackupRsc"] = "💾 Config-Backup (.rsc)…",
        ["Det_BackupFull"] = "🗄️ Voll-Backup (.backup)…",
        ["Det_BackupDesc"] = "Config-Backup (.rsc): vollständige, lesbare Konfiguration über HTTPS – ohne Passwörter/Keys, ideal zum Versionieren, mit /import wiederherstellbar. Voll-Backup (.backup): exakte Binärkopie inkl. Passwörtern; Download je nach Einstellung über Web/WebFig oder SSH (nicht über die REST-API möglich).",

        // Status bar / messages (MainWindow)
        ["Status_Ready"] = "Bereit",
        ["Pub_Tooltip"] = "Öffentliche IP – klicken zum Kopieren",
        ["Msg_NoDevices"] = "Keine Geräte konfiguriert – mit «Scannen…» das Netzwerk durchsuchen oder «Hinzufügen» klicken.",
        ["Msg_SelectDeviceFirst"] = "Zuerst ein Gerät auswählen.",
        ["Msg_Querying"] = "Frage {0} Gerät(e) ab…",
        ["Msg_Discovering"] = "Suche im Netzwerk (MNDP, IPv4, IPv6)…",
        ["Msg_DiscoveryDone"] = "Suche abgeschlossen – {0} Geräte in der Liste.",
        ["Msg_SubnetTooBigAuto"] = "Subnetz zu gross für Auto-Scan ({0} Adressen) – MNDP/IPv6 laufen; Subnetz bei Bedarf manuell scannen.",
        ["Sc_SubnetSource"] = "von {0} ({1})",
        ["Tb_CycleAdapterTip"] = "Nächster Netzwerkadapter / Subnetz",
        ["Msg_OnlineSummary"] = "{0} – {1}/{2} Geräte online",
        ["Msg_UpdatesAvailableSuffix"] = ", {0} Update(s) verfügbar",
        ["Msg_DevicesAdded"] = "{0} Gerät(e) hinzugefügt.",
        ["Msg_DevicesUpdated"] = "{0} Gerät(e) aktualisiert.",
        ["Msg_RemoveConfirm"] = "«{0}» ({1}) wirklich aus der Überwachung entfernen?\nAm Gerät selbst wird nichts geändert.",
        ["Msg_RemoveTitle"] = "Gerät entfernen",
        ["Msg_LoadingLogs"] = "Lade Logs von {0}…",
        ["Msg_LogsLoaded"] = "{0} Logeinträge von {1} geladen.",
        ["Msg_LogsFailed"] = "Logs von {0} konnten nicht geladen werden: {1}",
        ["Msg_CheckingUpdatesAll"] = "Prüfe Updates auf allen Geräten…",
        ["Msg_UpdatesDoneSome"] = "Update-Prüfung abgeschlossen: {0} Gerät(e) mit verfügbarem Update.",
        ["Msg_UpdatesDoneNone"] = "Update-Prüfung abgeschlossen: alle Geräte aktuell (oder nicht erreichbar).",
        ["Msg_CheckingUpdateOne"] = "Prüfe Update auf {0}…",
        ["Msg_UpdateAvailableOne"] = "{0}: Update auf {1} verfügbar.",
        ["Msg_NoUpdateOne"] = "{0}: {1}",
        ["Msg_NoUpdateFallback"] = "kein Update verfügbar",
        ["Msg_SettingChannel"] = "Setze Kanal «{0}» auf {1} und prüfe Updates…",
        ["Msg_ChannelResult"] = "{0}: Kanal «{1}», {2}",
        ["Msg_ChannelUpdateAvail"] = "Update auf {0} verfügbar.",
        ["Msg_ChannelNoUpdate"] = "kein Update verfügbar.",
        ["Msg_ChannelFailed"] = "{0}: Kanalwechsel fehlgeschlagen – {1}",
        ["Msg_NoDevicesConfigured"] = "Keine Geräte konfiguriert.",
        ["Msg_SaveConfigFailed"] = "Konnte Konfiguration nicht speichern:\n{0}",

        // Backups (MainWindow)
        ["Msg_LoadingConfig"] = "Lade Konfiguration von {0}…",
        ["Msg_BackupFailed"] = "Backup von {0} fehlgeschlagen: {1}",
        ["Msg_BackupSaveTitle"] = "Config-Backup speichern",
        ["Msg_BackupCantLoad"] = "Konnte Konfiguration nicht laden:\n{0}",
        ["Msg_BackupSaved"] = "Backup von {0} gespeichert: {1}",
        ["Msg_SaveFailed"] = "Speichern fehlgeschlagen: {0}",
        ["Msg_SaveFailedTitle"] = "Config-Backup",
        ["Msg_SaveFileFailed"] = "Konnte Datei nicht speichern:\n{0}",
        ["Dlg_FolderTitle"] = "Zielordner für Config-Backups wählen",
        ["Msg_BackingUpAll"] = "Sichere Konfiguration von {0} Gerät(en)…",
        ["Msg_BackupAllDone"] = "Backups fertig: {0} gespeichert, {1} fehlgeschlagen. Ordner: {2}",
        ["Msg_BackupAllReport"] = "{0} von {1} Backups gespeichert in:\n{2}\n\nFehlgeschlagen:\n• {3}",
        ["Msg_BackupAllReportTitle"] = "Config-Backups",
        ["Dlg_RscFilter"] = "RouterOS-Export (*.rsc)|*.rsc|Textdatei (*.txt)|*.txt|Alle Dateien (*.*)|*.*",

        // Full backup (binary)
        ["Full_SaveTitle"] = "Voll-Backup (.backup) speichern",
        ["Full_Filter"] = "RouterOS-Backup (*.backup)|*.backup|Alle Dateien (*.*)|*.*",
        ["Full_Running"] = "Erstelle Voll-Backup auf {0} und lade es herunter…",
        ["Full_Saved"] = "Voll-Backup von {0} gespeichert: {1}",
        ["Full_Failed"] = "Voll-Backup von {0} fehlgeschlagen: {1}",
        ["Full_FailedTitle"] = "Voll-Backup",
        ["Full_FailedBody"] = "Voll-Backup fehlgeschlagen:\n{0}",

        // Edit/add device
        ["De_TitleAdd"] = "Gerät hinzufügen",
        ["De_TitleEdit"] = "Gerät bearbeiten",
        ["De_TitleEditMulti"] = "Mehrere Geräte bearbeiten",
        ["De_MultiBanner"] = "Mehrere Geräte ausgewählt – die folgenden Einstellungen werden auf alle angewendet (Name und Adresse bleiben unverändert).",
        ["De_Name"] = "Name:",
        ["De_Address"] = "Adresse (IP/Host):",
        ["De_Connection"] = "Verbindung:",
        ["De_Https"] = "HTTPS",
        ["De_Port"] = "Port:",
        ["De_IgnoreCert"] = "Zertifikatsfehler ignorieren",
        ["De_User"] = "Benutzer:",
        ["De_Password"] = "Passwort:",
        ["De_Monitor"] = "Automatisch überwachen (Auto-Abfrage)",
        ["De_Notes"] = "Notizen:",
        ["De_PwHint"] = "Leer lassen = bisheriges Passwort behalten.",
        ["De_Test"] = "Verbindung testen",
        ["De_Ok"] = "OK",
        ["De_Cancel"] = "Abbrechen",
        ["De_Connecting"] = "Verbinde…",
        ["De_TestOk"] = "✔ Verbunden: {0} – {1}, RouterOS {2}",
        ["De_TestErr"] = "✘ Fehler: {0}",
        ["De_HttpHint"] = "\n💡 Das Gerät antwortet aber via HTTP (Port 80): Entweder den Haken bei HTTPS entfernen, oder auf dem Gerät www-ssl ein Zertifikat zuweisen (Rezept im README).",
        ["De_ErrAddressEmpty"] = "Adresse darf nicht leer sein.",
        ["De_ErrPort"] = "Ungültiger Port.",
        ["De_Vendor"] = "Typ / Vendor:",
        ["De_Model"] = "Modell:",
        ["De_HwRev"] = "HW-Rev.:",
        ["De_TpLinkHint"] = "TP-Link wird per SSH abgefragt (Port = SSH-Port). Modell/Revision füllen die Firmware-Seite, z. B. tl-sg2008 / v3.",
        ["De_TestOkTp"] = "✔ Verbunden: {0}, HW {1}, Firmware {2}",
        ["Det_FirmwarePage"] = "🌐 Firmware-Seite…",

        // Scan
        ["Sc_Title"] = "Netzwerk scannen",
        ["Sc_Mndp"] = "📡 MNDP-Discovery (MikroTik im LAN)",
        ["Sc_Subnet"] = "Subnetz:",
        ["Sc_ScanBtn"] = "🔍 Subnetz scannen",
        ["Sc_TargetsTip"] = "Subnetz (192.168.1.0/24), Bereich (192.168.1.50-100) oder einzelne IP – mehrere mit Komma getrennt.",
        ["Sc_Stop"] = "⏹ Stopp",
        ["Sc_Intro"] = "MNDP findet MikroTik-Geräte per Broadcast; der Subnetz-Scan findet zusätzlich andere Geräte (Ping + Port-Check).",
        ["Sc_DefaultCreds"] = "Standard-Zugangsdaten für neue Geräte (optional):",
        ["Sc_User"] = "Benutzer:",
        ["Sc_Password"] = "Passwort:",
        ["Sc_AddSelected"] = "Ausgewählte hinzufügen",
        ["Sc_Close"] = "Schliessen",
        ["Col_Ip"] = "IP",
        ["Col_Identity"] = "Identity",
        ["Col_Mac"] = "MAC",
        ["Col_Source"] = "Quelle",
        ["Col_Hint"] = "Hinweis",
        ["Col_Services"] = "Dienste",
        ["Col_DeviceType"] = "Typ",
        ["Dev_Router"] = "Router",
        ["Dev_Switch"] = "Switch",
        ["Dev_AccessPoint"] = "Access Point",
        ["Dev_Printer"] = "Drucker",
        ["Dev_Nas"] = "NAS",
        ["Dev_Pc"] = "PC",
        ["Dev_Phone"] = "Telefon",
        ["Dev_Camera"] = "Kamera",
        ["Dev_IoT"] = "IoT",
        ["Dev_Server"] = "Server",
        ["Sc_MndpRunning"] = "MNDP-Discovery läuft (5 Sekunden)…",
        ["Sc_MndpDone"] = "MNDP-Discovery abgeschlossen: {0} MikroTik-Gerät(e) gefunden.",
        ["Sc_MndpBusy"] = "MNDP nicht möglich (Port 5678 belegt? Winbox/The Dude offen?): {0}",
        ["Sc_MndpError"] = "MNDP-Fehler: {0}",
        ["Sc_Scanning"] = "Scanne {0} ({1} Adressen)…",
        ["Sc_ScanProgress"] = "Scanne {0}: {1}/{2} geprüft, {3} Gerät(e) gefunden…",
        ["Sc_ScanDone"] = "Scan abgeschlossen: {0} erreichbare(s) Gerät(e) in {1}.",
        ["Sc_Ipv6Discover"] = "📡 IPv6-Nachbarn suchen",
        ["Sc_Ipv6Intro"] = "Pingt ff02::1 und liest den Neighbor-Cache (ND). Zeigt Geräte, mit denen das System schon Kontakt hatte.",
        ["Sc_Ipv6Running"] = "Suche IPv6-Nachbarn… (bis zu 15 s, läuft weiter)",
        ["Sc_Ipv6Done"] = "IPv6-Discovery abgeschlossen: {0} Nachbar(n).",
        ["Sc_Ipv6Error"] = "IPv6-Fehler: {0}",
        ["Sc_ScanCancelled"] = "Scan abgebrochen.",
        ["Sc_ScanError"] = "Scan-Fehler: {0}",
        ["Sc_NoneSelected"] = "Keine Geräte ausgewählt.",
        ["Sc_HintAlreadyAdded"] = "bereits in der Geräteliste",
        ["Sc_HintLikely"] = "vermutlich MikroTik",
        ["Sc_SmbHeader"] = "SMB-Freigaben:",
        ["Sc_SmbLoading"] = "lädt…",
        ["Sc_SmbNone"] = "keine sichtbaren Freigaben",
        ["Sc_SmbTimeout"] = "Zeitüberschreitung beim Abfragen",
        ["Sc_SmbDenied"] = "Zugriff verweigert – Anmeldung/Rechte nötig",
        ["Sc_HintPorts"] = "Ports: {0}",
        ["Sc_GatewayModel"] = "Gateway: {0}",
        ["Sc_HintWebServer"] = "Web: {0}",
        ["Val_Na"] = "k. A.",

        // Mass update
        ["Ua_Title"] = "Updates installieren",
        ["Ua_UseDefaultChannel"] = "Standard-Kanal für alle:",
        ["Ua_UseDefaultChannelHint"] = "sonst nutzt jedes Gerät seinen eigenen Kanal (Spalte).",
        ["Ua_SettingChannel"] = "Setze Kanal «{0}» und prüfe…",
        ["Ua_Warn"] = "Achtung: Jedes Update rebootet das Gerät. Die Installation läuft sequenziell in der Reihenfolge der Liste – Geräte am Netzwerkrand (APs, Switches) zuerst, den Uplink-Router zuletzt, sonst sägt man den Ast ab, auf dem die restlichen Geräte erreichbar sind. Reihenfolge mit ▲/▼ anpassen.",
        ["Ua_WaitOnline"] = "Warten bis Gerät wieder online",
        ["Ua_ContinueOnError"] = "Bei Fehler mit nächstem Gerät weiterfahren",
        ["Ua_Start"] = "▶ Start",
        ["Ua_Stop"] = "⏹ Stopp",
        ["Ua_Close"] = "Schliessen",
        ["Col_Device"] = "Gerät",
        ["Col_Installed"] = "Installiert",
        ["Col_State"] = "Stand",
        ["Ua_ConfirmBody"] = "Jetzt {0} Gerät(e) nacheinander aktualisieren?\nJedes Gerät wird dabei neu gestartet.",
        ["Ua_ConfirmTitle"] = "Updates installieren",
        ["Ua_NoneSelected"] = "Keine Geräte angehakt.",
        ["Ua_StopRequested"] = "Stopp angefordert – aktueller Schritt wird noch beendet…",
        ["Ua_CloseWhileRunning"] = "Lauf zuerst mit «Stopp» beenden.",
        ["Ua_Done"] = "— Fertig: {0} aktualisiert, {1} fehlgeschlagen. —",
        ["Ua_Stopped"] = "— Lauf gestoppt. —",
        ["Ua_AbortOnError"] = "Abbruch wegen Fehler (Option «Bei Fehler weiterfahren» ist aus).",
        ["Ua_DeviceHeader"] = "══ {0} ({1}) ══",
        ["Ua_Checking"] = "Prüfe auf Updates…",
        ["Ua_CheckFailed"] = "✘ Update-Prüfung fehlgeschlagen: {0}",
        ["Ua_AlreadyCurrent"] = "Bereits aktuell – übersprungen.",
        ["Ua_StateCheck"] = "Prüfe Update…",
        ["Ua_StateCheckFailed"] = "Prüfung fehlgeschlagen: {0}",
        ["Ua_StateCurrent"] = "bereits aktuell",
        ["Ua_StateInstalling"] = "Installiere {0}…",
        ["Ua_Installing"] = "Installiere Update auf {0} – Gerät lädt Pakete und rebootet…",
        ["Ua_InstallFailed"] = "✘ Installation fehlgeschlagen: {0}",
        ["Ua_StateInstallFailed"] = "Installation fehlgeschlagen: {0}",
        ["Ua_StateStarted"] = "Update gestartet",
        ["Ua_StartedNoWait"] = "Update gestartet (ohne Warten auf Reboot).",
        ["Ua_StateWaiting"] = "Warte auf Reboot…",
        ["Ua_StateWaitingSec"] = "Warte auf Reboot… (noch {0} s)",
        ["Ua_BackOnline"] = "✔ {0} ist wieder online, Version {1}.",
        ["Ua_StateDone"] = "✔ Fertig – Version {0}",
        ["Ua_StateTimeout"] = "✘ Nicht wieder erreichbar (Timeout)",
        ["Ua_Timeout"] = "✘ {0} war nach {1} Minuten nicht wieder erreichbar.",
        ["Ua_StateUpdateAvail"] = "Update verfügbar",

        // Settings
        ["Set_Title"] = "Einstellungen",
        ["Set_Language"] = "Sprache:",
        ["Set_LangSystem"] = "System (Windows)",
        ["Set_LangGerman"] = "Deutsch",
        ["Set_LangEnglish"] = "Englisch",
        ["Set_LangSwiss"] = "Schweizerdeutsch",
        ["Set_LangHint"] = "Sprachänderung wirkt sofort.",
        ["Set_BackupMethod"] = "Voll-Backup-Methode (.backup):",
        ["Set_BackupAuto"] = "Automatisch (Web, sonst SSH)",
        ["Set_BackupWeb"] = "Web (WebFig)",
        ["Set_BackupSsh"] = "SSH (SCP)",
        ["Set_SshPort"] = "SSH-Port:",
        ["Set_BackupInfo"] = "Das binäre .backup lässt sich nicht über die REST-API holen. «Web» spricht MikroTiks WebFig-Protokoll (wie der Browser) – derzeit noch nicht verfügbar, weicht auf SSH aus. «SSH» nutzt den ab Werk aktiven, verschlüsselten SSH-Dienst (SCP). Der reine Config-Export (.rsc) braucht nichts davon und läuft immer über HTTPS.",
        ["Set_Save"] = "Speichern",
        ["Set_Cancel"] = "Abbrechen",
        ["Set_Reset"] = "TikMan-Konfiguration zurücksetzen…",
        ["Ctx_CopyVendorFull"] = "Ganzen Hersteller-Eintrag kopieren",
        ["Vi_Title"] = "Hersteller (OUI)",
        ["Vi_Copy"] = "Kopieren",
        ["Msg_Copied"] = "In die Zwischenablage kopiert.",
        ["De_Channel"] = "Update-Kanal:",
        ["Upd_ChannelDefault"] = "(Standard)",
        ["Set_DefaultChannel"] = "Standard-Update-Kanal:",
        ["Tab_Available"] = "Verfügbare Updates",
        ["Upd_InstalledRow"] = "Installiert",
        ["Set_IgnoreCert"] = "Unsichere HTTPS-Zertifikate erlauben",
        ["Set_IgnoreCertHint"] = "Empfohlen im LAN: MikroTik verwendet ab Werk ein selbstsigniertes Zertifikat. Aus lässt HTTPS-Verbindungen mit ungültigem Zertifikat fehlschlagen.",
        ["Set_AllowHttp"] = "Anmeldung über unsicheres HTTP erlauben",
        ["Set_AllowHttpHint"] = "Nur in vertrauenswürdigen Netzen! Geräte, deren HTTPS fehlschlägt, werden bei der nächsten Abfrage auf HTTP umgestellt – Zugangsdaten gehen dann im Klartext übers Netz.",
        ["Set_ForceMailto"] = "Problem-Report immer über die Standard-Mail-App (mailto) senden",
        ["Set_ForceMailtoHint"] = "Aus: bevorzugt Outlook (klassisch) mit Datei-Anhang, sonst automatischer Fallback auf die Standard-Mail-App (Log im Text).",
        ["Tb_ReportProblem"] = "🐞 Problem melden",
        ["Rep_Subject"] = "TikMan Problem-Report {0}",
        ["Rep_Body"] = "Bitte das Problem hier kurz beschreiben. Das Diagnose-Log ist beigefügt.",
        ["Rep_Opened"] = "E-Mail-Entwurf geöffnet – Log angehängt.",
        ["Rep_OpenedFallback"] = "E-Mail geöffnet (Log im Text). Ganzes Log: {0}",
        ["Rep_Failed"] = "Konnte keine E-Mail-App öffnen. Log gespeichert: {0}",
        ["Rep_FullLog"] = "ganzes Log",
        ["Tb_RequestFeature"] = "💡 Feature vorschlagen",
        ["Feat_Subject"] = "TikMan Feature-Wunsch {0}",
        ["Feat_Body"] = "Beschreibe hier die gewünschte Funktion so genau wie möglich.",
        ["Feat_Opened"] = "E-Mail für den Feature-Wunsch geöffnet.",
        ["Feat_Failed"] = "Konnte keine E-Mail-App öffnen.",
        ["Set_PersistList"] = "Geräteliste in der Konfiguration speichern",
        ["Set_PersistHint"] = "Aus: Geräte gelten nur für diese Sitzung. Ein: Beim Start werden die gespeicherten Geräte neu auf Erreichbarkeit geprüft; nicht erreichbare Zeilen erscheinen rot.",
        ["Set_ResetConfirm"] = "Alle Einstellungen und Geräte löschen und auf Werkszustand zurücksetzen?\nDie Konfigurationsdatei (Passwörter etc.) wird entfernt. Das kann nicht rückgängig gemacht werden.",
        ["Set_ResetDone"] = "Auf Werkszustand zurückgesetzt.",
        ["Set_OuiTitle"] = "MAC-Hersteller-Datenbank (OUI)",
        ["Set_OuiInfo"] = "Die IEEE-Liste ist eingebaut. Für die neueste Version herunterladen – sie wird als oui.txt neben die exe gelegt und beim nächsten Start bevorzugt.",
        ["Set_OuiDownload"] = "Neueste OUI-Liste herunterladen",
        ["Set_OuiDownloading"] = "Lädt…",
        ["Set_OuiDone"] = "Gespeichert: {0} (wirkt beim nächsten Start)",
        ["Set_OuiFailed"] = "Download fehlgeschlagen: {0}",
    };

    public static readonly Dictionary<string, string> English = new()
    {
        // Toolbar
        ["Tb_Scan"] = "🔍 Scan…",
        ["Tb_Add"] = "➕ Add",
        ["Tb_Edit"] = "✏️ Edit",
        ["Tb_Remove"] = "🗑️ Remove",
        ["Tb_RefreshAll"] = "🔄 Refresh all",
        ["Tb_BackupAll"] = "💾 Save backups…",
        ["Tb_CheckUpdates"] = "📦 Check updates",
        ["Tb_InstallUpdates"] = "⬆️ Install updates…",
        ["Tb_Settings"] = "⚙️ Settings…",
        ["Tb_AutoRefresh"] = "Auto-refresh every",

        // Device table
        ["Col_Name"] = "Name",
        ["Col_Address"] = "Address",
        ["Col_Board"] = "Model",
        ["Col_Version"] = "Version",
        ["Col_Latest"] = "Latest",
        ["Col_Cpu"] = "CPU",
        ["Col_Ram"] = "RAM",
        ["Col_Uptime"] = "Uptime",
        ["Col_LastError"] = "Last error",

        // Tabs
        ["Tab_Logs"] = "Logs",
        ["Tab_Monitoring"] = "CPU / memory load",
        ["Tab_Update"] = "Update",
        ["Tab_Details"] = "Details",

        // Logs
        ["Logs_Load"] = "🔄 Refresh logs",
        ["Logs_Auto"] = "Auto (3 s)",
        ["Filter_Tip"] = "Filters the list – every entered word must appear in the row.",
        ["View_Tip"] = "Combine a device's IPv4 and IPv6 address into one row.",
        ["View_Combine"] = "Combine IPv4/IPv6",
        ["Logs_Count"] = "Count:",
        ["Logs_All"] = "all",
        ["Logs_Filter"] = "Filter:",
        ["Col_Time"] = "Time",
        ["Col_Topics"] = "Topics",
        ["Col_Message"] = "Message",

        // Monitoring
        ["Chart_NoData"] = "No samples yet – the device is recorded on the next refresh.",
        ["Col_MarkAllTip"] = "Select/deselect all",
        ["Msg_NoDevicesMarked"] = "No devices marked – tick the devices in the list.",
        ["Msg_HttpFallbackTitle"] = "Try HTTP?",
        ["Col_InstalledRel"] = "Installed rel.",
        ["Col_UpdateRel"] = "Update rel.",
        ["Msg_HttpFallbackPrompt"] = "{0} device(s) could not connect via HTTPS.\n\nTry HTTP instead?\n\nWARNING: credentials and data are then sent in clear text – use only on a trusted network.",
        ["Col_Vendor"] = "Vendor",
        ["Col_MacVendor"] = "MAC vendor",
        ["Col_Protocol"] = "Supported protocols",
        ["Sc_Clear"] = "🗑️ Clear",
        ["Sc_CredsHint"] = "New devices use the default credentials from Settings.",
        ["Set_DefaultPwHint"] = "Leave empty to keep the current password.",

        // Device status / short update status
        ["St_Online"] = "Online",
        ["St_Offline"] = "Offline",
        ["St_Busy"] = "Busy…",
        ["St_Unknown"] = "Unknown",
        ["Upd_CheckFailedStatus"] = "Check failed",
        ["Upd_ChannelFailedStatus"] = "Channel switch failed",

        // Update tab
        ["Upd_Installed"] = "Installed version:",
        ["Upd_Latest"] = "Latest version:",
        ["Upd_Channel"] = "Channel:",
        ["Upd_Status"] = "Status:",
        ["Upd_ChannelLabel"] = "Update channel:",
        ["Upd_ChannelHint"] = "Selection is applied and checked immediately.",
        ["Upd_Check"] = "Check update",
        ["Upd_Install"] = "Install update (reboots!)",
        ["Upd_Note"] = "Note: A RouterOS update downloads the packages and reboots the device. For several devices use the «Install updates…» assistant in the toolbar – it installs sequentially and waits until each device is back online.",
        ["Upd_RightsBox"] = "Required permissions of the API user:\n• Monitoring/logs/checking updates only: read, rest-api\n• Switch channel & install update: additionally write, reboot, test\n• Config backup (.rsc): via HTTPS with write (temporary export file) – no FTP needed\n• Full backup (.backup) via SSH: additionally ssh, ftp (SSH service enabled)",

        // Details tab
        ["Det_Connection"] = "Connection:",
        ["Det_User"] = "User:",
        ["Det_Mac"] = "MAC:",
        ["Det_Notes"] = "Notes:",
        ["Det_Edit"] = "✏️ Edit device…",
        ["Det_BackupRsc"] = "💾 Config backup (.rsc)…",
        ["Det_BackupFull"] = "🗄️ Full backup (.backup)…",
        ["Det_BackupDesc"] = "Config backup (.rsc): complete, readable configuration over HTTPS – without passwords/keys, ideal for versioning, restorable with /import. Full backup (.backup): exact binary copy incl. passwords; downloaded via Web/WebFig or SSH depending on settings (not possible through the REST API).",

        // Status bar / messages (MainWindow)
        ["Status_Ready"] = "Ready",
        ["Pub_Tooltip"] = "Public IP – click to copy",
        ["Msg_NoDevices"] = "No devices configured – use «Scan…» to search the network or click «Add».",
        ["Msg_SelectDeviceFirst"] = "Select a device first.",
        ["Msg_Querying"] = "Querying {0} device(s)…",
        ["Msg_Discovering"] = "Discovering on the network (MNDP, IPv4, IPv6)…",
        ["Msg_DiscoveryDone"] = "Discovery finished – {0} devices in the list.",
        ["Msg_SubnetTooBigAuto"] = "Subnet too large for auto-scan ({0} addresses) – MNDP/IPv6 ran; scan the subnet manually if needed.",
        ["Sc_SubnetSource"] = "from {0} ({1})",
        ["Tb_CycleAdapterTip"] = "Next network adapter / subnet",
        ["Msg_OnlineSummary"] = "{0} – {1}/{2} devices online",
        ["Msg_UpdatesAvailableSuffix"] = ", {0} update(s) available",
        ["Msg_DevicesAdded"] = "{0} device(s) added.",
        ["Msg_DevicesUpdated"] = "{0} device(s) updated.",
        ["Msg_RemoveConfirm"] = "Really remove «{0}» ({1}) from monitoring?\nNothing is changed on the device itself.",
        ["Msg_RemoveTitle"] = "Remove device",
        ["Msg_LoadingLogs"] = "Loading logs from {0}…",
        ["Msg_LogsLoaded"] = "Loaded {0} log entries from {1}.",
        ["Msg_LogsFailed"] = "Could not load logs from {0}: {1}",
        ["Msg_CheckingUpdatesAll"] = "Checking updates on all devices…",
        ["Msg_UpdatesDoneSome"] = "Update check finished: {0} device(s) with an available update.",
        ["Msg_UpdatesDoneNone"] = "Update check finished: all devices up to date (or unreachable).",
        ["Msg_CheckingUpdateOne"] = "Checking update on {0}…",
        ["Msg_UpdateAvailableOne"] = "{0}: update to {1} available.",
        ["Msg_NoUpdateOne"] = "{0}: {1}",
        ["Msg_NoUpdateFallback"] = "no update available",
        ["Msg_SettingChannel"] = "Setting channel «{0}» on {1} and checking updates…",
        ["Msg_ChannelResult"] = "{0}: channel «{1}», {2}",
        ["Msg_ChannelUpdateAvail"] = "update to {0} available.",
        ["Msg_ChannelNoUpdate"] = "no update available.",
        ["Msg_ChannelFailed"] = "{0}: channel switch failed – {1}",
        ["Msg_NoDevicesConfigured"] = "No devices configured.",
        ["Msg_SaveConfigFailed"] = "Could not save configuration:\n{0}",

        // Backups (MainWindow)
        ["Msg_LoadingConfig"] = "Loading configuration from {0}…",
        ["Msg_BackupFailed"] = "Backup of {0} failed: {1}",
        ["Msg_BackupSaveTitle"] = "Save config backup",
        ["Msg_BackupCantLoad"] = "Could not load configuration:\n{0}",
        ["Msg_BackupSaved"] = "Backup of {0} saved: {1}",
        ["Msg_SaveFailed"] = "Saving failed: {0}",
        ["Msg_SaveFailedTitle"] = "Config backup",
        ["Msg_SaveFileFailed"] = "Could not save file:\n{0}",
        ["Dlg_FolderTitle"] = "Choose target folder for config backups",
        ["Msg_BackingUpAll"] = "Backing up configuration of {0} device(s)…",
        ["Msg_BackupAllDone"] = "Backups done: {0} saved, {1} failed. Folder: {2}",
        ["Msg_BackupAllReport"] = "{0} of {1} backups saved to:\n{2}\n\nFailed:\n• {3}",
        ["Msg_BackupAllReportTitle"] = "Config backups",
        ["Dlg_RscFilter"] = "RouterOS export (*.rsc)|*.rsc|Text file (*.txt)|*.txt|All files (*.*)|*.*",

        // Full backup (binary)
        ["Full_SaveTitle"] = "Save full backup (.backup)",
        ["Full_Filter"] = "RouterOS backup (*.backup)|*.backup|All files (*.*)|*.*",
        ["Full_Running"] = "Creating full backup on {0} and downloading it…",
        ["Full_Saved"] = "Full backup of {0} saved: {1}",
        ["Full_Failed"] = "Full backup of {0} failed: {1}",
        ["Full_FailedTitle"] = "Full backup",
        ["Full_FailedBody"] = "Full backup failed:\n{0}",

        // Edit/add device
        ["De_TitleAdd"] = "Add device",
        ["De_TitleEdit"] = "Edit device",
        ["De_TitleEditMulti"] = "Edit multiple devices",
        ["De_MultiBanner"] = "Multiple devices selected – the settings below are applied to all of them (name and address stay unchanged).",
        ["De_Name"] = "Name:",
        ["De_Address"] = "Address (IP/host):",
        ["De_Connection"] = "Connection:",
        ["De_Https"] = "HTTPS",
        ["De_Port"] = "Port:",
        ["De_IgnoreCert"] = "Ignore certificate errors",
        ["De_User"] = "User:",
        ["De_Password"] = "Password:",
        ["De_Monitor"] = "Monitor automatically (auto-refresh)",
        ["De_Notes"] = "Notes:",
        ["De_PwHint"] = "Leave empty = keep current password.",
        ["De_Test"] = "Test connection",
        ["De_Ok"] = "OK",
        ["De_Cancel"] = "Cancel",
        ["De_Connecting"] = "Connecting…",
        ["De_TestOk"] = "✔ Connected: {0} – {1}, RouterOS {2}",
        ["De_TestErr"] = "✘ Error: {0}",
        ["De_HttpHint"] = "\n💡 The device does answer via HTTP (port 80): either untick HTTPS, or assign a certificate to www-ssl on the device (recipe in the README).",
        ["De_ErrAddressEmpty"] = "Address must not be empty.",
        ["De_ErrPort"] = "Invalid port.",
        ["De_Vendor"] = "Type / vendor:",
        ["De_Model"] = "Model:",
        ["De_HwRev"] = "HW rev.:",
        ["De_TpLinkHint"] = "TP-Link is queried over SSH (port = SSH port). Model/revision drive the firmware page, e.g. tl-sg2008 / v3.",
        ["De_TestOkTp"] = "✔ Connected: {0}, HW {1}, firmware {2}",
        ["Det_FirmwarePage"] = "🌐 Firmware page…",

        // Scan
        ["Sc_Title"] = "Scan network",
        ["Sc_Mndp"] = "📡 MNDP discovery (MikroTik on LAN)",
        ["Sc_Subnet"] = "Subnet:",
        ["Sc_ScanBtn"] = "🔍 Scan subnet",
        ["Sc_TargetsTip"] = "Subnet (192.168.1.0/24), range (192.168.1.50-100) or single IP – separate several with commas.",
        ["Sc_Stop"] = "⏹ Stop",
        ["Sc_Intro"] = "MNDP finds MikroTik devices via broadcast; the subnet scan also finds other devices (ping + port check).",
        ["Sc_DefaultCreds"] = "Default credentials for new devices (optional):",
        ["Sc_User"] = "User:",
        ["Sc_Password"] = "Password:",
        ["Sc_AddSelected"] = "Add selected",
        ["Sc_Close"] = "Close",
        ["Col_Ip"] = "IP",
        ["Col_Identity"] = "Identity",
        ["Col_Mac"] = "MAC",
        ["Col_Source"] = "Source",
        ["Col_Hint"] = "Hint",
        ["Col_Services"] = "Services",
        ["Col_DeviceType"] = "Type",
        ["Dev_Router"] = "Router",
        ["Dev_Switch"] = "Switch",
        ["Dev_AccessPoint"] = "Access point",
        ["Dev_Printer"] = "Printer",
        ["Dev_Nas"] = "NAS",
        ["Dev_Pc"] = "PC",
        ["Dev_Phone"] = "Phone",
        ["Dev_Camera"] = "Camera",
        ["Dev_IoT"] = "IoT",
        ["Dev_Server"] = "Server",
        ["Sc_MndpRunning"] = "MNDP discovery running (5 seconds)…",
        ["Sc_MndpDone"] = "MNDP discovery finished: {0} MikroTik device(s) found.",
        ["Sc_MndpBusy"] = "MNDP not possible (port 5678 in use? Winbox/The Dude open?): {0}",
        ["Sc_MndpError"] = "MNDP error: {0}",
        ["Sc_Scanning"] = "Scanning {0} ({1} addresses)…",
        ["Sc_ScanProgress"] = "Scanning {0}: {1}/{2} checked, {3} device(s) found…",
        ["Sc_ScanDone"] = "Scan finished: {0} reachable device(s) in {1}.",
        ["Sc_Ipv6Discover"] = "📡 Discover IPv6 neighbors",
        ["Sc_Ipv6Intro"] = "Pings ff02::1 and reads the neighbor cache (ND). Shows devices the system has already talked to.",
        ["Sc_Ipv6Running"] = "Discovering IPv6 neighbors… (up to 15 s, keeps running)",
        ["Sc_Ipv6Done"] = "IPv6 discovery finished: {0} neighbor(s).",
        ["Sc_Ipv6Error"] = "IPv6 error: {0}",
        ["Sc_ScanCancelled"] = "Scan cancelled.",
        ["Sc_ScanError"] = "Scan error: {0}",
        ["Sc_NoneSelected"] = "No devices selected.",
        ["Sc_HintAlreadyAdded"] = "already in device list",
        ["Sc_HintLikely"] = "probably MikroTik",
        ["Sc_SmbHeader"] = "SMB shares:",
        ["Sc_SmbLoading"] = "loading…",
        ["Sc_SmbNone"] = "no visible shares",
        ["Sc_SmbTimeout"] = "timed out",
        ["Sc_SmbDenied"] = "access denied – login/rights required",
        ["Sc_HintPorts"] = "Ports: {0}",
        ["Sc_GatewayModel"] = "Gateway: {0}",
        ["Sc_HintWebServer"] = "Web: {0}",
        ["Val_Na"] = "n/a",

        // Mass update
        ["Ua_Title"] = "Install updates",
        ["Ua_UseDefaultChannel"] = "Default channel for all:",
        ["Ua_UseDefaultChannelHint"] = "otherwise each device uses its own channel (column).",
        ["Ua_SettingChannel"] = "Setting channel «{0}» and checking…",
        ["Ua_Warn"] = "Warning: Every update reboots the device. Installation runs sequentially in list order – edge devices (APs, switches) first, the uplink router last, otherwise you cut off the branch the remaining devices hang on. Reorder with ▲/▼.",
        ["Ua_WaitOnline"] = "Wait until device is back online",
        ["Ua_ContinueOnError"] = "Continue with next device on error",
        ["Ua_Start"] = "▶ Start",
        ["Ua_Stop"] = "⏹ Stop",
        ["Ua_Close"] = "Close",
        ["Col_Device"] = "Device",
        ["Col_Installed"] = "Installed",
        ["Col_State"] = "State",
        ["Ua_ConfirmBody"] = "Update {0} device(s) one after another now?\nEach device will be rebooted.",
        ["Ua_ConfirmTitle"] = "Install updates",
        ["Ua_NoneSelected"] = "No devices ticked.",
        ["Ua_StopRequested"] = "Stop requested – finishing the current step…",
        ["Ua_CloseWhileRunning"] = "Stop the run with «Stop» first.",
        ["Ua_Done"] = "— Done: {0} updated, {1} failed. —",
        ["Ua_Stopped"] = "— Run stopped. —",
        ["Ua_AbortOnError"] = "Aborting due to error (option «Continue on error» is off).",
        ["Ua_DeviceHeader"] = "══ {0} ({1}) ══",
        ["Ua_Checking"] = "Checking for updates…",
        ["Ua_CheckFailed"] = "✘ Update check failed: {0}",
        ["Ua_AlreadyCurrent"] = "Already up to date – skipped.",
        ["Ua_StateCheck"] = "Checking update…",
        ["Ua_StateCheckFailed"] = "Check failed: {0}",
        ["Ua_StateCurrent"] = "already up to date",
        ["Ua_StateInstalling"] = "Installing {0}…",
        ["Ua_Installing"] = "Installing update to {0} – device downloads packages and reboots…",
        ["Ua_InstallFailed"] = "✘ Installation failed: {0}",
        ["Ua_StateInstallFailed"] = "Installation failed: {0}",
        ["Ua_StateStarted"] = "Update started",
        ["Ua_StartedNoWait"] = "Update started (without waiting for reboot).",
        ["Ua_StateWaiting"] = "Waiting for reboot…",
        ["Ua_StateWaitingSec"] = "Waiting for reboot… ({0} s left)",
        ["Ua_BackOnline"] = "✔ {0} is back online, version {1}.",
        ["Ua_StateDone"] = "✔ Done – version {0}",
        ["Ua_StateTimeout"] = "✘ Not reachable again (timeout)",
        ["Ua_Timeout"] = "✘ {0} was not reachable again after {1} minutes.",
        ["Ua_StateUpdateAvail"] = "Update available",

        // Settings
        ["Set_Title"] = "Settings",
        ["Set_Language"] = "Language:",
        ["Set_LangSystem"] = "System (Windows)",
        ["Set_LangGerman"] = "German",
        ["Set_LangEnglish"] = "English",
        ["Set_LangSwiss"] = "Swiss German",
        ["Set_LangHint"] = "Language change takes effect immediately.",
        ["Set_BackupMethod"] = "Full backup method (.backup):",
        ["Set_BackupAuto"] = "Automatic (web, else SSH)",
        ["Set_BackupWeb"] = "Web (WebFig)",
        ["Set_BackupSsh"] = "SSH (SCP)",
        ["Set_SshPort"] = "SSH port:",
        ["Set_BackupInfo"] = "The binary .backup cannot be fetched through the REST API. «Web» speaks MikroTik's WebFig protocol (like the browser) – currently not yet available, falls back to SSH. «SSH» uses the factory-enabled, encrypted SSH service (SCP). The plain config export (.rsc) needs none of this and always runs over HTTPS.",
        ["Set_Save"] = "Save",
        ["Set_Cancel"] = "Cancel",
        ["Set_Reset"] = "Reset TikMan configuration…",
        ["Ctx_CopyVendorFull"] = "Copy full vendor entry",
        ["Vi_Title"] = "Vendor (OUI)",
        ["Vi_Copy"] = "Copy",
        ["Msg_Copied"] = "Copied to clipboard.",
        ["De_Channel"] = "Update channel:",
        ["Upd_ChannelDefault"] = "(Default)",
        ["Set_DefaultChannel"] = "Default update channel:",
        ["Tab_Available"] = "Available updates",
        ["Upd_InstalledRow"] = "Installed",
        ["Set_IgnoreCert"] = "Allow insecure HTTPS certificates",
        ["Set_IgnoreCertHint"] = "Recommended on a LAN: MikroTik ships with a self-signed certificate. Off makes HTTPS connections with an invalid certificate fail.",
        ["Set_AllowHttp"] = "Allow login over insecure HTTP",
        ["Set_AllowHttpHint"] = "Trusted networks only! Devices whose HTTPS fails are switched to HTTP on the next refresh – credentials then travel over the network in clear text.",
        ["Set_ForceMailto"] = "Always send the problem report via the default mail app (mailto)",
        ["Set_ForceMailtoHint"] = "Off: prefers Outlook Classic with a file attachment, otherwise falls back to the default mail app (log inline).",
        ["Tb_ReportProblem"] = "🐞 Report a problem",
        ["Rep_Subject"] = "TikMan problem report {0}",
        ["Rep_Body"] = "Please describe the problem here. The diagnostic log is attached.",
        ["Rep_Opened"] = "E-mail draft opened – log attached.",
        ["Rep_OpenedFallback"] = "E-mail opened (log inline). Full log: {0}",
        ["Rep_Failed"] = "Could not open a mail app. Log saved: {0}",
        ["Rep_FullLog"] = "full log",
        ["Tb_RequestFeature"] = "💡 Request a feature",
        ["Feat_Subject"] = "TikMan feature request {0}",
        ["Feat_Body"] = "Please describe the feature you'd like as precisely as possible.",
        ["Feat_Opened"] = "Feature-request e-mail opened.",
        ["Feat_Failed"] = "Could not open a mail app.",
        ["Set_PersistList"] = "Save the device list in the configuration",
        ["Set_PersistHint"] = "Off: devices exist only for this session. On: stored devices are re-checked for reachability at startup; unreachable rows appear red.",
        ["Set_ResetConfirm"] = "Delete all settings and devices and reset to defaults?\nThe config file (passwords etc.) is removed. This cannot be undone.",
        ["Set_ResetDone"] = "Reset to defaults.",
        ["Set_OuiTitle"] = "MAC vendor database (OUI)",
        ["Set_OuiInfo"] = "The IEEE list is built in. Download the newest version – it is stored as oui.txt next to the exe and preferred on the next start.",
        ["Set_OuiDownload"] = "Download latest OUI list",
        ["Set_OuiDownloading"] = "Downloading…",
        ["Set_OuiDone"] = "Saved: {0} (applies on next start)",
        ["Set_OuiFailed"] = "Download failed: {0}",
    };

    // Swiss German (Zurich-leaning, no official spelling)
    public static readonly Dictionary<string, string> SwissGerman = new()
    {
        // Toolbar
        ["Tb_Scan"] = "🔍 Scanne…",
        ["Tb_Add"] = "➕ Dezuätue",
        ["Tb_Edit"] = "✏️ Bearbeite",
        ["Tb_Remove"] = "🗑️ Ewägtue",
        ["Tb_RefreshAll"] = "🔄 Alli abfrage",
        ["Tb_BackupAll"] = "💾 Backups sichere…",
        ["Tb_CheckUpdates"] = "📦 Updates prüefe",
        ["Tb_InstallUpdates"] = "⬆️ Updates installiere…",
        ["Tb_Settings"] = "⚙️ Iistellige…",
        ["Tb_AutoRefresh"] = "Auto-Abfrag alli",

        // Device table
        ["Col_Name"] = "Name",
        ["Col_Address"] = "Adrässe",
        ["Col_Board"] = "Modäll",
        ["Col_Version"] = "Version",
        ["Col_Latest"] = "Nöischti",
        ["Col_Cpu"] = "CPU",
        ["Col_Ram"] = "RAM",
        ["Col_Uptime"] = "Uptime",
        ["Col_LastError"] = "Letschtä Fähler",

        // Tabs
        ["Tab_Logs"] = "Logs",
        ["Tab_Monitoring"] = "CPU / RAM-Lascht",
        ["Tab_Update"] = "Update",
        ["Tab_Details"] = "Details",

        // Logs
        ["Logs_Load"] = "🔄 Logs aktualisiere",
        ["Logs_Auto"] = "Auto (3 s)",
        ["Filter_Tip"] = "Filteret d Lischtä – alli iigäh Wörter müend im Iitrag vorcho.",
        ["View_Tip"] = "IPv4- und IPv6-Adrässe vom gliichä Grät i einer Ziile zämäfassä.",
        ["View_Combine"] = "IPv4/IPv6 zämäfassä",
        ["Logs_Count"] = "Aazahl:",
        ["Logs_All"] = "alli",
        ["Logs_Filter"] = "Filter:",
        ["Col_Time"] = "Ziit",
        ["Col_Topics"] = "Topics",
        ["Col_Message"] = "Mäldig",

        // Monitoring
        ["Chart_NoData"] = "Na kei Mässwärt – s Grät wird bim nächschtä Abfrage erfasst.",
        ["Col_MarkAllTip"] = "Alli us-/abwähle",
        ["Msg_NoDevicesMarked"] = "Kei Grät markiert – Grät i de Lischtä ahögglä.",
        ["Msg_HttpFallbackTitle"] = "HTTP versuechä?",
        ["Col_InstalledRel"] = "Installiert (Rel.)",
        ["Col_UpdateRel"] = "Update (Rel.)",
        ["Msg_HttpFallbackPrompt"] = "{0} Grät händ sich nöd per HTTPS chönä verbindä.\n\nStattdessä HTTP versuechä?\n\nWARNIG: Zugangsdatä und Datä gönd dänn im Klartext übers Netz – nur in emä vertrauenswürdigä Netz bruuche.",
        ["Col_Vendor"] = "Hersteller",
        ["Col_MacVendor"] = "MAC-Hersteller",
        ["Col_Protocol"] = "Unterstützti Protokoll",
        ["Sc_Clear"] = "🗑️ Lääre",
        ["Sc_CredsHint"] = "Nöii Grät bruuched d Standard-Zugangsdatä us de Iistellige.",
        ["Set_DefaultPwHint"] = "Läär lah = aktuells Passwort behalte.",

        // Grätstatus / churzi Update-Status
        ["St_Online"] = "Online",
        ["St_Offline"] = "Offline",
        ["St_Busy"] = "Bschäftiget…",
        ["St_Unknown"] = "Unbekannt",
        ["Upd_CheckFailedStatus"] = "Prüefig fählgschlage",
        ["Upd_ChannelFailedStatus"] = "Kanalwächsel fählgschlage",

        // Update tab
        ["Upd_Installed"] = "Installierti Version:",
        ["Upd_Latest"] = "Nöischti Version:",
        ["Upd_Channel"] = "Kanal:",
        ["Upd_Status"] = "Status:",
        ["Upd_ChannelLabel"] = "Update-Kanal:",
        ["Upd_ChannelHint"] = "D Uswahl wird sofort gsetzt und prüeft.",
        ["Upd_Check"] = "Update prüefe",
        ["Upd_Install"] = "Update installiere (rebootet!)",
        ["Upd_Note"] = "Hiiwiis: Es RouterOS-Update ladt d Päckli abä und startet s Grät neu. Für mehreri Grät de Assischtänt «Updates installiere…» i de Wärchzüügleischtä bruuche – dört wird sequenziell installiert und gwartet, bis jedes Grät wieder online isch.",
        ["Upd_RightsBox"] = "Nötigi Rächt vom API-Benutzer:\n• Nur Überwache/Logs/Update prüefe: read, rest-api\n• Kanal wächsle & Update installiere: zusätzlich write, reboot, test\n• Config-Backup (.rsc): über HTTPS mit write (temporäri Exportdatei) – kei FTP nötig\n• Voll-Backup (.backup) via SSH: zusätzlich ssh, ftp (SSH-Dienscht aktiv)",

        // Details tab
        ["Det_Connection"] = "Verbindig:",
        ["Det_User"] = "Benutzer:",
        ["Det_Mac"] = "MAC:",
        ["Det_Notes"] = "Notizä:",
        ["Det_Edit"] = "✏️ Grät bearbeite…",
        ["Det_BackupRsc"] = "💾 Config-Backup (.rsc)…",
        ["Det_BackupFull"] = "🗄️ Voll-Backup (.backup)…",
        ["Det_BackupDesc"] = "Config-Backup (.rsc): vollständigi, läsbari Konfiguration über HTTPS – ohni Passwörter/Keys, ideal zum Versioniere, mit /import wiederherstellbar. Voll-Backup (.backup): exakti Binärkopie inkl. Passwörter; Download je nach Iistellig über Web/WebFig oder SSH (nöd über d REST-API möglich).",

        // Status bar / messages
        ["Status_Ready"] = "Parat",
        ["Pub_Tooltip"] = "Öffentlichi IP – klicke zum Kopiere",
        ["Msg_NoDevices"] = "Kei Grät konfiguriert – mit «Scanne…» s Netzwärk duresuäche oder «Dezuätue» klicke.",
        ["Msg_SelectDeviceFirst"] = "Zerscht es Grät uswähle.",
        ["Msg_Querying"] = "Frag {0} Grät ab…",
        ["Msg_Discovering"] = "Sueche im Netzwärk (MNDP, IPv4, IPv6)…",
        ["Msg_DiscoveryDone"] = "Sueche fertig – {0} Grät i de Lischtä.",
        ["Msg_SubnetTooBigAuto"] = "Subnetz z gross für Auto-Scan ({0} Adrässe) – MNDP/IPv6 laufed; s Subnetz bi Bedarf manuell scannä.",
        ["Sc_SubnetSource"] = "vo {0} ({1})",
        ["Tb_CycleAdapterTip"] = "Nächschtä Netzwärkadapter / Subnetz",
        ["Msg_OnlineSummary"] = "{0} – {1}/{2} Grät online",
        ["Msg_UpdatesAvailableSuffix"] = ", {0} Update(s) verfüegbar",
        ["Msg_DevicesAdded"] = "{0} Grät dezuätah.",
        ["Msg_DevicesUpdated"] = "{0} Grät aktualisiert.",
        ["Msg_RemoveConfirm"] = "«{0}» ({1}) würkli us de Überwachig ewägtue?\nAm Grät sälber wird nüt gänderet.",
        ["Msg_RemoveTitle"] = "Grät ewägtue",
        ["Msg_LoadingLogs"] = "Lade Logs vo {0}…",
        ["Msg_LogsLoaded"] = "{0} Logiiträg vo {1} glade.",
        ["Msg_LogsFailed"] = "Logs vo {0} händ nöd chönä glade werde: {1}",
        ["Msg_CheckingUpdatesAll"] = "Prüefe Updates uf allnä Grät…",
        ["Msg_UpdatesDoneSome"] = "Update-Prüefig fertig: {0} Grät mit verfüegbarem Update.",
        ["Msg_UpdatesDoneNone"] = "Update-Prüefig fertig: alli Grät aktuell (oder nöd erreichbar).",
        ["Msg_CheckingUpdateOne"] = "Prüefe Update uf {0}…",
        ["Msg_UpdateAvailableOne"] = "{0}: Update uf {1} verfüegbar.",
        ["Msg_NoUpdateOne"] = "{0}: {1}",
        ["Msg_NoUpdateFallback"] = "kei Update verfüegbar",
        ["Msg_SettingChannel"] = "Setze Kanal «{0}» uf {1} und prüefe Updates…",
        ["Msg_ChannelResult"] = "{0}: Kanal «{1}», {2}",
        ["Msg_ChannelUpdateAvail"] = "Update uf {0} verfüegbar.",
        ["Msg_ChannelNoUpdate"] = "kei Update verfüegbar.",
        ["Msg_ChannelFailed"] = "{0}: Kanalwächsel fählgschlage – {1}",
        ["Msg_NoDevicesConfigured"] = "Kei Grät konfiguriert.",
        ["Msg_SaveConfigFailed"] = "Ha d Konfiguration nöd chönä speichere:\n{0}",

        // Backups
        ["Msg_LoadingConfig"] = "Lade Konfiguration vo {0}…",
        ["Msg_BackupFailed"] = "Backup vo {0} fählgschlage: {1}",
        ["Msg_BackupSaveTitle"] = "Config-Backup speichere",
        ["Msg_BackupCantLoad"] = "Ha d Konfiguration nöd chönä lade:\n{0}",
        ["Msg_BackupSaved"] = "Backup vo {0} gspeicheret: {1}",
        ["Msg_SaveFailed"] = "Speichere fählgschlage: {0}",
        ["Msg_SaveFailedTitle"] = "Config-Backup",
        ["Msg_SaveFileFailed"] = "Ha d Datei nöd chönä speichere:\n{0}",
        ["Dlg_FolderTitle"] = "Zielordner für Config-Backups wähle",
        ["Msg_BackingUpAll"] = "Sichere Konfiguration vo {0} Grät…",
        ["Msg_BackupAllDone"] = "Backups fertig: {0} gspeicheret, {1} fählgschlage. Ordner: {2}",
        ["Msg_BackupAllReport"] = "{0} vo {1} Backups gspeicheret i:\n{2}\n\nFählgschlage:\n• {3}",
        ["Msg_BackupAllReportTitle"] = "Config-Backups",
        ["Dlg_RscFilter"] = "RouterOS-Export (*.rsc)|*.rsc|Textdatei (*.txt)|*.txt|Alli Dateiä (*.*)|*.*",

        // Full backup (binary)
        ["Full_SaveTitle"] = "Voll-Backup (.backup) speichere",
        ["Full_Filter"] = "RouterOS-Backup (*.backup)|*.backup|Alli Dateiä (*.*)|*.*",
        ["Full_Running"] = "Erstelle Voll-Backup uf {0} und lade s abä…",
        ["Full_Saved"] = "Voll-Backup vo {0} gspeicheret: {1}",
        ["Full_Failed"] = "Voll-Backup vo {0} fählgschlage: {1}",
        ["Full_FailedTitle"] = "Voll-Backup",
        ["Full_FailedBody"] = "Voll-Backup fählgschlage:\n{0}",

        // Edit/add device
        ["De_TitleAdd"] = "Grät dezuätue",
        ["De_TitleEdit"] = "Grät bearbeite",
        ["De_TitleEditMulti"] = "Mehreri Grät bearbeite",
        ["De_MultiBanner"] = "Mehreri Grät uswählt – di undere Iistellige wärded uf alli aagwendet (Name und Adrässe blibed unveränderet).",
        ["De_Name"] = "Name:",
        ["De_Address"] = "Adrässe (IP/Host):",
        ["De_Connection"] = "Verbindig:",
        ["De_Https"] = "HTTPS",
        ["De_Port"] = "Port:",
        ["De_IgnoreCert"] = "Zertifikatsfähler ignoriere",
        ["De_User"] = "Benutzer:",
        ["De_Password"] = "Passwort:",
        ["De_Monitor"] = "Automatisch überwache (Auto-Abfrag)",
        ["De_Notes"] = "Notizä:",
        ["De_PwHint"] = "Läär lah = bisherigs Passwort behalte.",
        ["De_Test"] = "Verbindig teste",
        ["De_Ok"] = "OK",
        ["De_Cancel"] = "Abbräche",
        ["De_Connecting"] = "Verbinde…",
        ["De_TestOk"] = "✔ Verbunde: {0} – {1}, RouterOS {2}",
        ["De_TestErr"] = "✘ Fähler: {0}",
        ["De_HttpHint"] = "\n💡 S Grät antwortet aber via HTTP (Port 80): Entweder de Haggä bi HTTPS ewägtue, oder am Grät em www-ssl es Zertifikat zuewiise (Rezäpt im README).",
        ["De_ErrAddressEmpty"] = "D Adrässe dörf nöd läär sii.",
        ["De_ErrPort"] = "Ungültigä Port.",
        ["De_Vendor"] = "Typ / Vendor:",
        ["De_Model"] = "Modäll:",
        ["De_HwRev"] = "HW-Rev.:",
        ["De_TpLinkHint"] = "TP-Link wird per SSH abgfrägt (Port = SSH-Port). Modäll/Revision fülled d Firmware-Sitä, z.B. tl-sg2008 / v3.",
        ["De_TestOkTp"] = "✔ Verbunde: {0}, HW {1}, Firmware {2}",
        ["Det_FirmwarePage"] = "🌐 Firmware-Sitä…",

        // Scan
        ["Sc_Title"] = "Netzwärk scanne",
        ["Sc_Mndp"] = "📡 MNDP-Discovery (MikroTik im LAN)",
        ["Sc_Subnet"] = "Subnetz:",
        ["Sc_ScanBtn"] = "🔍 Subnetz scanne",
        ["Sc_TargetsTip"] = "Subnetz (192.168.1.0/24), Bereich (192.168.1.50-100) oder einzelni IP – mehreri mit Komma getrännt.",
        ["Sc_Stop"] = "⏹ Stopp",
        ["Sc_Intro"] = "MNDP findet MikroTik-Grät per Broadcast; de Subnetz-Scan findet zusätzlich anderi Grät (Ping + Port-Check).",
        ["Sc_DefaultCreds"] = "Standard-Zugangsdatä für nöii Grät (optional):",
        ["Sc_User"] = "Benutzer:",
        ["Sc_Password"] = "Passwort:",
        ["Sc_AddSelected"] = "Uswählti dezuätue",
        ["Sc_Close"] = "Zuemache",
        ["Col_Ip"] = "IP",
        ["Col_Identity"] = "Identity",
        ["Col_Mac"] = "MAC",
        ["Col_Source"] = "Quelle",
        ["Col_Hint"] = "Hiiwiis",
        ["Col_Services"] = "Dienscht",
        ["Col_DeviceType"] = "Typ",
        ["Dev_Router"] = "Router",
        ["Dev_Switch"] = "Switch",
        ["Dev_AccessPoint"] = "Access Point",
        ["Dev_Printer"] = "Drucker",
        ["Dev_Nas"] = "NAS",
        ["Dev_Pc"] = "PC",
        ["Dev_Phone"] = "Telefon",
        ["Dev_Camera"] = "Kamera",
        ["Dev_IoT"] = "IoT",
        ["Dev_Server"] = "Server",
        ["Sc_MndpRunning"] = "MNDP-Discovery lauft (5 Sekundä)…",
        ["Sc_MndpDone"] = "MNDP-Discovery fertig: {0} MikroTik-Grät gfunde.",
        ["Sc_MndpBusy"] = "MNDP nöd möglich (Port 5678 blegt? Winbox/The Dude offe?): {0}",
        ["Sc_MndpError"] = "MNDP-Fähler: {0}",
        ["Sc_Scanning"] = "Scanne {0} ({1} Adrässe)…",
        ["Sc_ScanProgress"] = "Scanne {0}: {1}/{2} prüeft, {3} Grät gfunde…",
        ["Sc_ScanDone"] = "Scan fertig: {0} erreichbari Grät i {1}.",
        ["Sc_Ipv6Discover"] = "📡 IPv6-Nachbarä sueche",
        ["Sc_Ipv6Intro"] = "Pingt ff02::1 und liest de Neighbor-Cache (ND). Zeigt Grät wo s System scho Kontakt gha het.",
        ["Sc_Ipv6Running"] = "Sueche IPv6-Nachbarä… (bis zu 15 s, lauft wiiter)",
        ["Sc_Ipv6Done"] = "IPv6-Discovery fertig: {0} Nachbarä.",
        ["Sc_Ipv6Error"] = "IPv6-Fähler: {0}",
        ["Sc_ScanCancelled"] = "Scan abbroche.",
        ["Sc_ScanError"] = "Scan-Fähler: {0}",
        ["Sc_NoneSelected"] = "Kei Grät uswählt.",
        ["Sc_HintAlreadyAdded"] = "scho i de Grätlischtä",
        ["Sc_HintLikely"] = "vermuetlich MikroTik",
        ["Sc_SmbHeader"] = "SMB-Freigabä:",
        ["Sc_SmbLoading"] = "ladt…",
        ["Sc_SmbNone"] = "kei sichtbari Freigabä",
        ["Sc_SmbTimeout"] = "Zitüberschritig bim Abfrage",
        ["Sc_SmbDenied"] = "Zuegriff verweigeret – Aamäldig/Rächt nötig",
        ["Sc_HintPorts"] = "Ports: {0}",
        ["Sc_GatewayModel"] = "Gateway: {0}",
        ["Sc_HintWebServer"] = "Web: {0}",
        ["Val_Na"] = "k. A.",

        // Mass update
        ["Ua_Title"] = "Updates installiere",
        ["Ua_UseDefaultChannel"] = "Standard-Kanal für alli:",
        ["Ua_UseDefaultChannelHint"] = "susch bruucht jedes Grät sin eigät Kanal (Spaltä).",
        ["Ua_SettingChannel"] = "Setze Kanal «{0}» und prüefe…",
        ["Ua_Warn"] = "Achtung: Jedes Update rebootet s Grät. D Installation lauft sequenziell i de Reihefolg vo de Lischtä – Grät am Netzwärkrand (APs, Switches) zerscht, de Uplink-Router zletscht, susch sägt mä de Ascht ab, wo di andere Grät dra hanged. Reihefolg mit ▲/▼ apasse.",
        ["Ua_WaitOnline"] = "Warte bis s Grät wieder online isch",
        ["Ua_ContinueOnError"] = "Bi Fähler mit em nächschtä Grät wiiterfahre",
        ["Ua_Start"] = "▶ Start",
        ["Ua_Stop"] = "⏹ Stopp",
        ["Ua_Close"] = "Zuemache",
        ["Col_Device"] = "Grät",
        ["Col_Installed"] = "Installiert",
        ["Col_State"] = "Stand",
        ["Ua_ConfirmBody"] = "Jetzt {0} Grät nachenand aktualisiere?\nJedes Grät wird debii neu gstartet.",
        ["Ua_ConfirmTitle"] = "Updates installiere",
        ["Ua_NoneSelected"] = "Kei Grät ahghäcklet.",
        ["Ua_StopRequested"] = "Stopp aagforderet – de aktuell Schritt wird na fertig gmacht…",
        ["Ua_CloseWhileRunning"] = "De Lauf zerscht mit «Stopp» beände.",
        ["Ua_Done"] = "— Fertig: {0} aktualisiert, {1} fählgschlage. —",
        ["Ua_Stopped"] = "— Lauf gstoppt. —",
        ["Ua_AbortOnError"] = "Abbruch wäge Fähler (Option «Bi Fähler wiiterfahre» isch us).",
        ["Ua_DeviceHeader"] = "══ {0} ({1}) ══",
        ["Ua_Checking"] = "Prüefe uf Updates…",
        ["Ua_CheckFailed"] = "✘ Update-Prüefig fählgschlage: {0}",
        ["Ua_AlreadyCurrent"] = "Scho aktuell – übersprunge.",
        ["Ua_StateCheck"] = "Prüefe Update…",
        ["Ua_StateCheckFailed"] = "Prüefig fählgschlage: {0}",
        ["Ua_StateCurrent"] = "scho aktuell",
        ["Ua_StateInstalling"] = "Installiere {0}…",
        ["Ua_Installing"] = "Installiere Update uf {0} – s Grät ladt Päckli und rebootet…",
        ["Ua_InstallFailed"] = "✘ Installation fählgschlage: {0}",
        ["Ua_StateInstallFailed"] = "Installation fählgschlage: {0}",
        ["Ua_StateStarted"] = "Update gstartet",
        ["Ua_StartedNoWait"] = "Update gstartet (ohni uf Reboot z'warte).",
        ["Ua_StateWaiting"] = "Warte uf Reboot…",
        ["Ua_StateWaitingSec"] = "Warte uf Reboot… (na {0} s)",
        ["Ua_BackOnline"] = "✔ {0} isch wieder online, Version {1}.",
        ["Ua_StateDone"] = "✔ Fertig – Version {0}",
        ["Ua_StateTimeout"] = "✘ Nöd wieder erreichbar (Timeout)",
        ["Ua_Timeout"] = "✘ {0} isch nach {1} Minutä nöd wieder erreichbar gsii.",
        ["Ua_StateUpdateAvail"] = "Update verfüegbar",

        // Settings
        ["Set_Title"] = "Iistellige",
        ["Set_Language"] = "Sprach:",
        ["Set_LangSystem"] = "System (Windows)",
        ["Set_LangGerman"] = "Dütsch",
        ["Set_LangEnglish"] = "Änglisch",
        ["Set_LangSwiss"] = "Schwiizerdütsch",
        ["Set_LangHint"] = "D Sprachänderig wirkt sofort.",
        ["Set_BackupMethod"] = "Voll-Backup-Methode (.backup):",
        ["Set_BackupAuto"] = "Automatisch (Web, susch SSH)",
        ["Set_BackupWeb"] = "Web (WebFig)",
        ["Set_BackupSsh"] = "SSH (SCP)",
        ["Set_SshPort"] = "SSH-Port:",
        ["Set_BackupInfo"] = "S binäri .backup chan mä nöd über d REST-API hole. «Web» redt MikroTiks WebFig-Protokoll (wiä de Browser) – zurzit na nöd verfüegbar, wiicht uf SSH us. «SSH» bruucht de ab Werk aktiv, verschlüsslet SSH-Dienscht (SCP). De reini Config-Export (.rsc) bruucht nüt devo und lauft immer über HTTPS.",
        ["Set_Save"] = "Speichere",
        ["Set_Cancel"] = "Abbräche",
        ["Set_Reset"] = "TikMan-Konfiguration zrucksetzä…",
        ["Ctx_CopyVendorFull"] = "Ganzä Hersteller-Iitrag kopiere",
        ["Vi_Title"] = "Hersteller (OUI)",
        ["Vi_Copy"] = "Kopiere",
        ["Msg_Copied"] = "I d Zwüschäablag kopiert.",
        ["De_Channel"] = "Update-Kanal:",
        ["Upd_ChannelDefault"] = "(Standard)",
        ["Set_DefaultChannel"] = "Standard-Update-Kanal:",
        ["Tab_Available"] = "Verfüegbari Updates",
        ["Upd_InstalledRow"] = "Installiert",
        ["Set_IgnoreCert"] = "Unsicheri HTTPS-Zertifikat erlaube",
        ["Set_IgnoreCertHint"] = "Empfohlä im LAN: MikroTik bruucht ab Werk es sälbstsignierts Zertifikat. Us lat HTTPS-Verbindige mit ungültigem Zertifikat fählschlah.",
        ["Set_AllowHttp"] = "Aamäldig über unsichers HTTP erlaube",
        ["Set_AllowHttpHint"] = "Nur i vertrauenswürdigä Netz! Grät wo HTTPS fählschlat, wärded bi de nächschtä Abfrag uf HTTP umgstellt – Zugangsdatä gönd dänn im Klartext übers Netz.",
        ["Set_ForceMailto"] = "Problem-Report immer über d Standard-Mail-App (mailto) schickä",
        ["Set_ForceMailtoHint"] = "Us: bevorzugt Outlook (klassisch) mit Datei-Aahang, susch automatischä Fallback uf d Standard-Mail-App (Log im Text).",
        ["Tb_ReportProblem"] = "🐞 Problem mäldä",
        ["Rep_Subject"] = "TikMan Problem-Report {0}",
        ["Rep_Body"] = "Bitte s Problem da churz beschriibä. S Diagnose-Log isch dra.",
        ["Rep_Opened"] = "E-Mail-Entwurf uf – Log aaghänkt.",
        ["Rep_OpenedFallback"] = "E-Mail uf (Log im Text). Ganzes Log: {0}",
        ["Rep_Failed"] = "Ha kei Mail-App chönä öffnä. Log gspeicheret: {0}",
        ["Rep_FullLog"] = "ganzes Log",
        ["Tb_RequestFeature"] = "💡 Feature vorschlah",
        ["Feat_Subject"] = "TikMan Feature-Wunsch {0}",
        ["Feat_Body"] = "Beschriib da di gwünschti Funktion so gnau wiä möglich.",
        ["Feat_Opened"] = "E-Mail für dä Feature-Wunsch uf.",
        ["Feat_Failed"] = "Ha kei Mail-App chönä öffnä.",
        ["Set_PersistList"] = "Grätlischtä i de Konfiguration speichere",
        ["Set_PersistHint"] = "Us: Grät gälted nur für die Sitzig. Aa: Bim Start wärded di gspeichertä Grät neu uf Erreichbarkeit prüeft; nöd erreichbari Zilä erschined rot.",
        ["Set_ResetConfirm"] = "Alli Iistellige und Grät löschä und uf Werkszuestand zrucksetzä?\nD Konfigdatei (Passwörter etc.) wird entfernt. Cha mä nöd rückgängig mache.",
        ["Set_ResetDone"] = "Uf Werkszuestand zruckgsetzt.",
        ["Set_OuiTitle"] = "MAC-Hersteller-Datebank (OUI)",
        ["Set_OuiInfo"] = "D IEEE-Lischtä isch iigboue. Für d nöischt Version abälade – sie wird als oui.txt näbä d exe gleit und bim nächschtä Start bevorzugt.",
        ["Set_OuiDownload"] = "Nöischti OUI-Lischtä abälade",
        ["Set_OuiDownloading"] = "Ladt…",
        ["Set_OuiDone"] = "Gspeicheret: {0} (wirkt bim nächschtä Start)",
        ["Set_OuiFailed"] = "Download fählgschlage: {0}",
    };
}
